// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserLogin.proto
package com.commonSocket.application.message;

public final class UserLogin {

    private UserLogin() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }

    public interface UserLoginRequestOrBuilder
            extends com.google.protobuf.MessageOrBuilder {

        boolean hasUserName();

        String getUserName();

        // required string possWord = 2;
        boolean hasPossWord();

        String getPossWord();

        // required int32 screenWidth = 3;
        boolean hasScreenWidth();

        int getScreenWidth();

        // required int32 screenHeight = 4;
        boolean hasScreenHeight();

        int getScreenHeight();

        // optional string model = 5;
        boolean hasModel();

        String getModel();

        // optional string phone = 6;
        boolean hasPhone();

        String getPhone();

        // optional string sysVersion = 7;
        boolean hasSysVersion();

        String getSysVersion();

        // optional string connectType = 8;
        boolean hasConnectType();

        String getConnectType();

        // optional string IMEI = 9;
        boolean hasIMEI();

        String getIMEI();

        // optional string IMSI = 10;
        boolean hasIMSI();

        String getIMSI();

        // optional string language = 11;
        boolean hasLanguage();

        String getLanguage();

        // optional string version = 12;
        boolean hasVersion();

        String getVersion();

        // optional int32 appId = 13;
        boolean hasAppId();

        int getAppId();

        // optional int32 refId = 14;
        boolean hasRefId();

        int getRefId();
    }

    public static final class UserLoginRequest extends
            com.google.protobuf.GeneratedMessage
            implements UserLoginRequestOrBuilder {
        // Use UserLoginRequest.newBuilder() to construct.

        private UserLoginRequest(Builder builder) {
            super(builder);
        }

        private UserLoginRequest(boolean noInit) {
        }

        private static final UserLoginRequest defaultInstance;

        public static UserLoginRequest getDefaultInstance() {
            return defaultInstance;
        }

        public UserLoginRequest getDefaultInstanceForType() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
                getDescriptor() {
            return com.commonSocket.application.message.UserLogin.internal_static_message_UserLoginRequest_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
                internalGetFieldAccessorTable() {
            return com.commonSocket.application.message.UserLogin.internal_static_message_UserLoginRequest_fieldAccessorTable;
        }

        private int bitField0_;
        // required string userName = 1 [default = "powernpc"];
        public static final int USERNAME_FIELD_NUMBER = 1;
        private java.lang.Object userName_;

        public boolean hasUserName() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        public String getUserName() {
            java.lang.Object ref = userName_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs
                        = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    userName_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getUserNameBytes() {
            java.lang.Object ref = userName_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b
                        = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                userName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // required string possWord = 2;
        public static final int POSSWORD_FIELD_NUMBER = 2;
        private java.lang.Object possWord_;

        public boolean hasPossWord() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        public String getPossWord() {
            java.lang.Object ref = possWord_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs
                        = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    possWord_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getPossWordBytes() {
            java.lang.Object ref = possWord_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b
                        = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                possWord_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // required int32 screenWidth = 3;
        public static final int SCREENWIDTH_FIELD_NUMBER = 3;
        private int screenWidth_;

        public boolean hasScreenWidth() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        public int getScreenWidth() {
            return screenWidth_;
        }

        // required int32 screenHeight = 4;
        public static final int SCREENHEIGHT_FIELD_NUMBER = 4;
        private int screenHeight_;

        public boolean hasScreenHeight() {
            return ((bitField0_ & 0x00000008) == 0x00000008);
        }

        public int getScreenHeight() {
            return screenHeight_;
        }

        // optional string model = 5;
        public static final int MODEL_FIELD_NUMBER = 5;
        private java.lang.Object model_;

        public boolean hasModel() {
            return ((bitField0_ & 0x00000010) == 0x00000010);
        }

        public String getModel() {
            java.lang.Object ref = model_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs
                        = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    model_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getModelBytes() {
            java.lang.Object ref = model_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b
                        = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                model_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // optional string phone = 6;
        public static final int PHONE_FIELD_NUMBER = 6;
        private java.lang.Object phone_;

        public boolean hasPhone() {
            return ((bitField0_ & 0x00000020) == 0x00000020);
        }

        public String getPhone() {
            java.lang.Object ref = phone_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs
                        = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    phone_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getPhoneBytes() {
            java.lang.Object ref = phone_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b
                        = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                phone_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // optional string sysVersion = 7;
        public static final int SYSVERSION_FIELD_NUMBER = 7;
        private java.lang.Object sysVersion_;

        public boolean hasSysVersion() {
            return ((bitField0_ & 0x00000040) == 0x00000040);
        }

        public String getSysVersion() {
            java.lang.Object ref = sysVersion_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs
                        = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    sysVersion_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getSysVersionBytes() {
            java.lang.Object ref = sysVersion_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b
                        = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                sysVersion_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // optional string connectType = 8;
        public static final int CONNECTTYPE_FIELD_NUMBER = 8;
        private java.lang.Object connectType_;

        public boolean hasConnectType() {
            return ((bitField0_ & 0x00000080) == 0x00000080);
        }

        public String getConnectType() {
            java.lang.Object ref = connectType_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs
                        = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    connectType_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getConnectTypeBytes() {
            java.lang.Object ref = connectType_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b
                        = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                connectType_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // optional string IMEI = 9;
        public static final int IMEI_FIELD_NUMBER = 9;
        private java.lang.Object iMEI_;

        public boolean hasIMEI() {
            return ((bitField0_ & 0x00000100) == 0x00000100);
        }

        public String getIMEI() {
            java.lang.Object ref = iMEI_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs
                        = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    iMEI_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getIMEIBytes() {
            java.lang.Object ref = iMEI_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b
                        = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                iMEI_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // optional string IMSI = 10;
        public static final int IMSI_FIELD_NUMBER = 10;
        private java.lang.Object iMSI_;

        public boolean hasIMSI() {
            return ((bitField0_ & 0x00000200) == 0x00000200);
        }

        public String getIMSI() {
            java.lang.Object ref = iMSI_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs
                        = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    iMSI_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getIMSIBytes() {
            java.lang.Object ref = iMSI_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b
                        = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                iMSI_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // optional string language = 11;
        public static final int LANGUAGE_FIELD_NUMBER = 11;
        private java.lang.Object language_;

        public boolean hasLanguage() {
            return ((bitField0_ & 0x00000400) == 0x00000400);
        }

        public String getLanguage() {
            java.lang.Object ref = language_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs
                        = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    language_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getLanguageBytes() {
            java.lang.Object ref = language_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b
                        = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                language_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // optional string version = 12;
        public static final int VERSION_FIELD_NUMBER = 12;
        private java.lang.Object version_;

        public boolean hasVersion() {
            return ((bitField0_ & 0x00000800) == 0x00000800);
        }

        public String getVersion() {
            java.lang.Object ref = version_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs
                        = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    version_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getVersionBytes() {
            java.lang.Object ref = version_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b
                        = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                version_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // optional int32 appId = 13;
        public static final int APPID_FIELD_NUMBER = 13;
        private int appId_;

        public boolean hasAppId() {
            return ((bitField0_ & 0x00001000) == 0x00001000);
        }

        public int getAppId() {
            return appId_;
        }

        // optional int32 refId = 14;
        public static final int REFID_FIELD_NUMBER = 14;
        private int refId_;

        public boolean hasRefId() {
            return ((bitField0_ & 0x00002000) == 0x00002000);
        }

        public int getRefId() {
            return refId_;
        }

        private void initFields() {
            userName_ = "powernpc";
            possWord_ = "";
            screenWidth_ = 0;
            screenHeight_ = 0;
            model_ = "";
            phone_ = "";
            sysVersion_ = "";
            connectType_ = "";
            iMEI_ = "";
            iMSI_ = "";
            language_ = "";
            version_ = "";
            appId_ = 0;
            refId_ = 0;
        }
        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) {
                return isInitialized == 1;
            }

            if (!hasUserName()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasPossWord()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasScreenWidth()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasScreenHeight()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(1, getUserNameBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(2, getPossWordBytes());
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeInt32(3, screenWidth_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                output.writeInt32(4, screenHeight_);
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                output.writeBytes(5, getModelBytes());
            }
            if (((bitField0_ & 0x00000020) == 0x00000020)) {
                output.writeBytes(6, getPhoneBytes());
            }
            if (((bitField0_ & 0x00000040) == 0x00000040)) {
                output.writeBytes(7, getSysVersionBytes());
            }
            if (((bitField0_ & 0x00000080) == 0x00000080)) {
                output.writeBytes(8, getConnectTypeBytes());
            }
            if (((bitField0_ & 0x00000100) == 0x00000100)) {
                output.writeBytes(9, getIMEIBytes());
            }
            if (((bitField0_ & 0x00000200) == 0x00000200)) {
                output.writeBytes(10, getIMSIBytes());
            }
            if (((bitField0_ & 0x00000400) == 0x00000400)) {
                output.writeBytes(11, getLanguageBytes());
            }
            if (((bitField0_ & 0x00000800) == 0x00000800)) {
                output.writeBytes(12, getVersionBytes());
            }
            if (((bitField0_ & 0x00001000) == 0x00001000)) {
                output.writeInt32(13, appId_);
            }
            if (((bitField0_ & 0x00002000) == 0x00002000)) {
                output.writeInt32(14, refId_);
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) {
                return size;
            }

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(1, getUserNameBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, getPossWordBytes());
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(3, screenWidth_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(4, screenHeight_);
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(5, getModelBytes());
            }
            if (((bitField0_ & 0x00000020) == 0x00000020)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(6, getPhoneBytes());
            }
            if (((bitField0_ & 0x00000040) == 0x00000040)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(7, getSysVersionBytes());
            }
            if (((bitField0_ & 0x00000080) == 0x00000080)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(8, getConnectTypeBytes());
            }
            if (((bitField0_ & 0x00000100) == 0x00000100)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(9, getIMEIBytes());
            }
            if (((bitField0_ & 0x00000200) == 0x00000200)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(10, getIMSIBytes());
            }
            if (((bitField0_ & 0x00000400) == 0x00000400)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(11, getLanguageBytes());
            }
            if (((bitField0_ & 0x00000800) == 0x00000800)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(12, getVersionBytes());
            }
            if (((bitField0_ & 0x00001000) == 0x00001000)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(13, appId_);
            }
            if (((bitField0_ & 0x00002000) == 0x00002000)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(14, refId_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static com.commonSocket.application.message.UserLogin.UserLoginRequest parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static com.commonSocket.application.message.UserLogin.UserLoginRequest parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static com.commonSocket.application.message.UserLogin.UserLoginRequest parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static com.commonSocket.application.message.UserLogin.UserLoginRequest parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static com.commonSocket.application.message.UserLogin.UserLoginRequest parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static com.commonSocket.application.message.UserLogin.UserLoginRequest parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static com.commonSocket.application.message.UserLogin.UserLoginRequest parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static com.commonSocket.application.message.UserLogin.UserLoginRequest parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static com.commonSocket.application.message.UserLogin.UserLoginRequest parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static com.commonSocket.application.message.UserLogin.UserLoginRequest parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(com.commonSocket.application.message.UserLogin.UserLoginRequest prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements com.commonSocket.application.message.UserLogin.UserLoginRequestOrBuilder {

            public static final com.google.protobuf.Descriptors.Descriptor
                    getDescriptor() {
                return com.commonSocket.application.message.UserLogin.internal_static_message_UserLoginRequest_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
                    internalGetFieldAccessorTable() {
                return com.commonSocket.application.message.UserLogin.internal_static_message_UserLoginRequest_fieldAccessorTable;
            }

            // Construct using com.powernpc.application.message.UserLogin.UserLoginRequest.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                userName_ = "powernpc";
                bitField0_ = (bitField0_ & ~0x00000001);
                possWord_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                screenWidth_ = 0;
                bitField0_ = (bitField0_ & ~0x00000004);
                screenHeight_ = 0;
                bitField0_ = (bitField0_ & ~0x00000008);
                model_ = "";
                bitField0_ = (bitField0_ & ~0x00000010);
                phone_ = "";
                bitField0_ = (bitField0_ & ~0x00000020);
                sysVersion_ = "";
                bitField0_ = (bitField0_ & ~0x00000040);
                connectType_ = "";
                bitField0_ = (bitField0_ & ~0x00000080);
                iMEI_ = "";
                bitField0_ = (bitField0_ & ~0x00000100);
                iMSI_ = "";
                bitField0_ = (bitField0_ & ~0x00000200);
                language_ = "";
                bitField0_ = (bitField0_ & ~0x00000400);
                version_ = "";
                bitField0_ = (bitField0_ & ~0x00000800);
                appId_ = 0;
                bitField0_ = (bitField0_ & ~0x00001000);
                refId_ = 0;
                bitField0_ = (bitField0_ & ~0x00002000);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
                    getDescriptorForType() {
                return com.commonSocket.application.message.UserLogin.UserLoginRequest.getDescriptor();
            }

            public com.commonSocket.application.message.UserLogin.UserLoginRequest getDefaultInstanceForType() {
                return com.commonSocket.application.message.UserLogin.UserLoginRequest.getDefaultInstance();
            }

            public com.commonSocket.application.message.UserLogin.UserLoginRequest build() {
                com.commonSocket.application.message.UserLogin.UserLoginRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            private com.commonSocket.application.message.UserLogin.UserLoginRequest buildParsed()
                    throws com.google.protobuf.InvalidProtocolBufferException {
                com.commonSocket.application.message.UserLogin.UserLoginRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(
                            result).asInvalidProtocolBufferException();
                }
                return result;
            }

            public com.commonSocket.application.message.UserLogin.UserLoginRequest buildPartial() {
                com.commonSocket.application.message.UserLogin.UserLoginRequest result = new com.commonSocket.application.message.UserLogin.UserLoginRequest(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.userName_ = userName_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.possWord_ = possWord_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.screenWidth_ = screenWidth_;
                if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
                    to_bitField0_ |= 0x00000008;
                }
                result.screenHeight_ = screenHeight_;
                if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
                    to_bitField0_ |= 0x00000010;
                }
                result.model_ = model_;
                if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
                    to_bitField0_ |= 0x00000020;
                }
                result.phone_ = phone_;
                if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
                    to_bitField0_ |= 0x00000040;
                }
                result.sysVersion_ = sysVersion_;
                if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
                    to_bitField0_ |= 0x00000080;
                }
                result.connectType_ = connectType_;
                if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
                    to_bitField0_ |= 0x00000100;
                }
                result.iMEI_ = iMEI_;
                if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
                    to_bitField0_ |= 0x00000200;
                }
                result.iMSI_ = iMSI_;
                if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
                    to_bitField0_ |= 0x00000400;
                }
                result.language_ = language_;
                if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
                    to_bitField0_ |= 0x00000800;
                }
                result.version_ = version_;
                if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
                    to_bitField0_ |= 0x00001000;
                }
                result.appId_ = appId_;
                if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
                    to_bitField0_ |= 0x00002000;
                }
                result.refId_ = refId_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.commonSocket.application.message.UserLogin.UserLoginRequest) {
                    return mergeFrom((com.commonSocket.application.message.UserLogin.UserLoginRequest) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.commonSocket.application.message.UserLogin.UserLoginRequest other) {
                if (other == com.commonSocket.application.message.UserLogin.UserLoginRequest.getDefaultInstance()) {
                    return this;
                }
                if (other.hasUserName()) {
                    setUserName(other.getUserName());
                }
                if (other.hasPossWord()) {
                    setPossWord(other.getPossWord());
                }
                if (other.hasScreenWidth()) {
                    setScreenWidth(other.getScreenWidth());
                }
                if (other.hasScreenHeight()) {
                    setScreenHeight(other.getScreenHeight());
                }
                if (other.hasModel()) {
                    setModel(other.getModel());
                }
                if (other.hasPhone()) {
                    setPhone(other.getPhone());
                }
                if (other.hasSysVersion()) {
                    setSysVersion(other.getSysVersion());
                }
                if (other.hasConnectType()) {
                    setConnectType(other.getConnectType());
                }
                if (other.hasIMEI()) {
                    setIMEI(other.getIMEI());
                }
                if (other.hasIMSI()) {
                    setIMSI(other.getIMSI());
                }
                if (other.hasLanguage()) {
                    setLanguage(other.getLanguage());
                }
                if (other.hasVersion()) {
                    setVersion(other.getVersion());
                }
                if (other.hasAppId()) {
                    setAppId(other.getAppId());
                }
                if (other.hasRefId()) {
                    setRefId(other.getRefId());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasUserName()) {

                    return false;
                }
                if (!hasPossWord()) {

                    return false;
                }
                if (!hasScreenWidth()) {

                    return false;
                }
                if (!hasScreenHeight()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.google.protobuf.UnknownFieldSet.Builder unknownFields
                        = com.google.protobuf.UnknownFieldSet.newBuilder(
                                this.getUnknownFields());
                while (true) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            this.setUnknownFields(unknownFields.build());
                            onChanged();
                            return this;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                this.setUnknownFields(unknownFields.build());
                                onChanged();
                                return this;
                            }
                            break;
                        }
                        case 10: {
                            bitField0_ |= 0x00000001;
                            userName_ = input.readBytes();
                            break;
                        }
                        case 18: {
                            bitField0_ |= 0x00000002;
                            possWord_ = input.readBytes();
                            break;
                        }
                        case 24: {
                            bitField0_ |= 0x00000004;
                            screenWidth_ = input.readInt32();
                            break;
                        }
                        case 32: {
                            bitField0_ |= 0x00000008;
                            screenHeight_ = input.readInt32();
                            break;
                        }
                        case 42: {
                            bitField0_ |= 0x00000010;
                            model_ = input.readBytes();
                            break;
                        }
                        case 50: {
                            bitField0_ |= 0x00000020;
                            phone_ = input.readBytes();
                            break;
                        }
                        case 58: {
                            bitField0_ |= 0x00000040;
                            sysVersion_ = input.readBytes();
                            break;
                        }
                        case 66: {
                            bitField0_ |= 0x00000080;
                            connectType_ = input.readBytes();
                            break;
                        }
                        case 74: {
                            bitField0_ |= 0x00000100;
                            iMEI_ = input.readBytes();
                            break;
                        }
                        case 82: {
                            bitField0_ |= 0x00000200;
                            iMSI_ = input.readBytes();
                            break;
                        }
                        case 90: {
                            bitField0_ |= 0x00000400;
                            language_ = input.readBytes();
                            break;
                        }
                        case 98: {
                            bitField0_ |= 0x00000800;
                            version_ = input.readBytes();
                            break;
                        }
                        case 104: {
                            bitField0_ |= 0x00001000;
                            appId_ = input.readInt32();
                            break;
                        }
                        case 112: {
                            bitField0_ |= 0x00002000;
                            refId_ = input.readInt32();
                            break;
                        }
                    }
                }
            }

            private int bitField0_;

            // required string userName = 1 [default = "powernpc"];
            private java.lang.Object userName_ = "powernpc";

            public boolean hasUserName() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            public String getUserName() {
                java.lang.Object ref = userName_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    userName_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            public Builder setUserName(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                userName_ = value;
                onChanged();
                return this;
            }

            public Builder clearUserName() {
                bitField0_ = (bitField0_ & ~0x00000001);
                userName_ = getDefaultInstance().getUserName();
                onChanged();
                return this;
            }

            void setUserName(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000001;
                userName_ = value;
                onChanged();
            }

            // required string possWord = 2;
            private java.lang.Object possWord_ = "";

            public boolean hasPossWord() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            public String getPossWord() {
                java.lang.Object ref = possWord_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    possWord_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            public Builder setPossWord(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                possWord_ = value;
                onChanged();
                return this;
            }

            public Builder clearPossWord() {
                bitField0_ = (bitField0_ & ~0x00000002);
                possWord_ = getDefaultInstance().getPossWord();
                onChanged();
                return this;
            }

            void setPossWord(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000002;
                possWord_ = value;
                onChanged();
            }

            // required int32 screenWidth = 3;
            private int screenWidth_;

            public boolean hasScreenWidth() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            public int getScreenWidth() {
                return screenWidth_;
            }

            public Builder setScreenWidth(int value) {
                bitField0_ |= 0x00000004;
                screenWidth_ = value;
                onChanged();
                return this;
            }

            public Builder clearScreenWidth() {
                bitField0_ = (bitField0_ & ~0x00000004);
                screenWidth_ = 0;
                onChanged();
                return this;
            }

            // required int32 screenHeight = 4;
            private int screenHeight_;

            public boolean hasScreenHeight() {
                return ((bitField0_ & 0x00000008) == 0x00000008);
            }

            public int getScreenHeight() {
                return screenHeight_;
            }

            public Builder setScreenHeight(int value) {
                bitField0_ |= 0x00000008;
                screenHeight_ = value;
                onChanged();
                return this;
            }

            public Builder clearScreenHeight() {
                bitField0_ = (bitField0_ & ~0x00000008);
                screenHeight_ = 0;
                onChanged();
                return this;
            }

            // optional string model = 5;
            private java.lang.Object model_ = "";

            public boolean hasModel() {
                return ((bitField0_ & 0x00000010) == 0x00000010);
            }

            public String getModel() {
                java.lang.Object ref = model_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    model_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            public Builder setModel(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000010;
                model_ = value;
                onChanged();
                return this;
            }

            public Builder clearModel() {
                bitField0_ = (bitField0_ & ~0x00000010);
                model_ = getDefaultInstance().getModel();
                onChanged();
                return this;
            }

            void setModel(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000010;
                model_ = value;
                onChanged();
            }

            // optional string phone = 6;
            private java.lang.Object phone_ = "";

            public boolean hasPhone() {
                return ((bitField0_ & 0x00000020) == 0x00000020);
            }

            public String getPhone() {
                java.lang.Object ref = phone_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    phone_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            public Builder setPhone(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000020;
                phone_ = value;
                onChanged();
                return this;
            }

            public Builder clearPhone() {
                bitField0_ = (bitField0_ & ~0x00000020);
                phone_ = getDefaultInstance().getPhone();
                onChanged();
                return this;
            }

            void setPhone(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000020;
                phone_ = value;
                onChanged();
            }

            // optional string sysVersion = 7;
            private java.lang.Object sysVersion_ = "";

            public boolean hasSysVersion() {
                return ((bitField0_ & 0x00000040) == 0x00000040);
            }

            public String getSysVersion() {
                java.lang.Object ref = sysVersion_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    sysVersion_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            public Builder setSysVersion(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000040;
                sysVersion_ = value;
                onChanged();
                return this;
            }

            public Builder clearSysVersion() {
                bitField0_ = (bitField0_ & ~0x00000040);
                sysVersion_ = getDefaultInstance().getSysVersion();
                onChanged();
                return this;
            }

            void setSysVersion(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000040;
                sysVersion_ = value;
                onChanged();
            }

            // optional string connectType = 8;
            private java.lang.Object connectType_ = "";

            public boolean hasConnectType() {
                return ((bitField0_ & 0x00000080) == 0x00000080);
            }

            public String getConnectType() {
                java.lang.Object ref = connectType_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    connectType_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            public Builder setConnectType(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000080;
                connectType_ = value;
                onChanged();
                return this;
            }

            public Builder clearConnectType() {
                bitField0_ = (bitField0_ & ~0x00000080);
                connectType_ = getDefaultInstance().getConnectType();
                onChanged();
                return this;
            }

            void setConnectType(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000080;
                connectType_ = value;
                onChanged();
            }

            // optional string IMEI = 9;
            private java.lang.Object iMEI_ = "";

            public boolean hasIMEI() {
                return ((bitField0_ & 0x00000100) == 0x00000100);
            }

            public String getIMEI() {
                java.lang.Object ref = iMEI_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    iMEI_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            public Builder setIMEI(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000100;
                iMEI_ = value;
                onChanged();
                return this;
            }

            public Builder clearIMEI() {
                bitField0_ = (bitField0_ & ~0x00000100);
                iMEI_ = getDefaultInstance().getIMEI();
                onChanged();
                return this;
            }

            void setIMEI(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000100;
                iMEI_ = value;
                onChanged();
            }

            // optional string IMSI = 10;
            private java.lang.Object iMSI_ = "";

            public boolean hasIMSI() {
                return ((bitField0_ & 0x00000200) == 0x00000200);
            }

            public String getIMSI() {
                java.lang.Object ref = iMSI_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    iMSI_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            public Builder setIMSI(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000200;
                iMSI_ = value;
                onChanged();
                return this;
            }

            public Builder clearIMSI() {
                bitField0_ = (bitField0_ & ~0x00000200);
                iMSI_ = getDefaultInstance().getIMSI();
                onChanged();
                return this;
            }

            void setIMSI(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000200;
                iMSI_ = value;
                onChanged();
            }

            // optional string language = 11;
            private java.lang.Object language_ = "";

            public boolean hasLanguage() {
                return ((bitField0_ & 0x00000400) == 0x00000400);
            }

            public String getLanguage() {
                java.lang.Object ref = language_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    language_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            public Builder setLanguage(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000400;
                language_ = value;
                onChanged();
                return this;
            }

            public Builder clearLanguage() {
                bitField0_ = (bitField0_ & ~0x00000400);
                language_ = getDefaultInstance().getLanguage();
                onChanged();
                return this;
            }

            void setLanguage(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000400;
                language_ = value;
                onChanged();
            }

            // optional string version = 12;
            private java.lang.Object version_ = "";

            public boolean hasVersion() {
                return ((bitField0_ & 0x00000800) == 0x00000800);
            }

            public String getVersion() {
                java.lang.Object ref = version_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    version_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            public Builder setVersion(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000800;
                version_ = value;
                onChanged();
                return this;
            }

            public Builder clearVersion() {
                bitField0_ = (bitField0_ & ~0x00000800);
                version_ = getDefaultInstance().getVersion();
                onChanged();
                return this;
            }

            void setVersion(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000800;
                version_ = value;
                onChanged();
            }

            // optional int32 appId = 13;
            private int appId_;

            public boolean hasAppId() {
                return ((bitField0_ & 0x00001000) == 0x00001000);
            }

            public int getAppId() {
                return appId_;
            }

            public Builder setAppId(int value) {
                bitField0_ |= 0x00001000;
                appId_ = value;
                onChanged();
                return this;
            }

            public Builder clearAppId() {
                bitField0_ = (bitField0_ & ~0x00001000);
                appId_ = 0;
                onChanged();
                return this;
            }

            // optional int32 refId = 14;
            private int refId_;

            public boolean hasRefId() {
                return ((bitField0_ & 0x00002000) == 0x00002000);
            }

            public int getRefId() {
                return refId_;
            }

            public Builder setRefId(int value) {
                bitField0_ |= 0x00002000;
                refId_ = value;
                onChanged();
                return this;
            }

            public Builder clearRefId() {
                bitField0_ = (bitField0_ & ~0x00002000);
                refId_ = 0;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:message.UserLoginRequest)
        }

        static {
            defaultInstance = new UserLoginRequest(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:message.UserLoginRequest)
    }

    public interface UserLoginResponseOrBuilder
            extends com.google.protobuf.MessageOrBuilder {

        // optional sint32 result = 1 [default = 0];
        boolean hasResult();

        int getResult();

        // optional string info = 2;
        boolean hasInfo();

        String getInfo();

        // optional uint64 verifyCode = 3;
        boolean hasVerifyCode();

        long getVerifyCode();

        // optional int32 updateAble = 4 [default = 0];
        boolean hasUpdateAble();

        int getUpdateAble();

        // optional string updateAddress = 5 [default = "http://192.168.1.1:80"];
        boolean hasUpdateAddress();

        String getUpdateAddress();
    }

    public static final class UserLoginResponse extends
            com.google.protobuf.GeneratedMessage
            implements UserLoginResponseOrBuilder {
        // Use UserLoginResponse.newBuilder() to construct.

        private UserLoginResponse(Builder builder) {
            super(builder);
        }

        private UserLoginResponse(boolean noInit) {
        }

        private static final UserLoginResponse defaultInstance;

        public static UserLoginResponse getDefaultInstance() {
            return defaultInstance;
        }

        public UserLoginResponse getDefaultInstanceForType() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
                getDescriptor() {
            return com.commonSocket.application.message.UserLogin.internal_static_message_UserLoginResponse_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
                internalGetFieldAccessorTable() {
            return com.commonSocket.application.message.UserLogin.internal_static_message_UserLoginResponse_fieldAccessorTable;
        }

        private int bitField0_;
        // optional sint32 result = 1 [default = 0];
        public static final int RESULT_FIELD_NUMBER = 1;
        private int result_;

        public boolean hasResult() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        public int getResult() {
            return result_;
        }

        // optional string info = 2;
        public static final int INFO_FIELD_NUMBER = 2;
        private java.lang.Object info_;

        public boolean hasInfo() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        public String getInfo() {
            java.lang.Object ref = info_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs
                        = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    info_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getInfoBytes() {
            java.lang.Object ref = info_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b
                        = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                info_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // optional uint64 verifyCode = 3;
        public static final int VERIFYCODE_FIELD_NUMBER = 3;
        private long verifyCode_;

        public boolean hasVerifyCode() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        public long getVerifyCode() {
            return verifyCode_;
        }

        // optional int32 updateAble = 4 [default = 0];
        public static final int UPDATEABLE_FIELD_NUMBER = 4;
        private int updateAble_;

        public boolean hasUpdateAble() {
            return ((bitField0_ & 0x00000008) == 0x00000008);
        }

        public int getUpdateAble() {
            return updateAble_;
        }

        // optional string updateAddress = 5 [default = "http://192.168.1.1:80"];
        public static final int UPDATEADDRESS_FIELD_NUMBER = 5;
        private java.lang.Object updateAddress_;

        public boolean hasUpdateAddress() {
            return ((bitField0_ & 0x00000010) == 0x00000010);
        }

        public String getUpdateAddress() {
            java.lang.Object ref = updateAddress_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs
                        = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    updateAddress_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getUpdateAddressBytes() {
            java.lang.Object ref = updateAddress_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b
                        = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                updateAddress_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private void initFields() {
            result_ = 0;
            info_ = "";
            verifyCode_ = 0L;
            updateAble_ = 0;
            updateAddress_ = "http://192.168.1.1:80";
        }
        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) {
                return isInitialized == 1;
            }

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeSInt32(1, result_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(2, getInfoBytes());
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeUInt64(3, verifyCode_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                output.writeInt32(4, updateAble_);
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                output.writeBytes(5, getUpdateAddressBytes());
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) {
                return size;
            }

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeSInt32Size(1, result_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, getInfoBytes());
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(3, verifyCode_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(4, updateAble_);
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(5, getUpdateAddressBytes());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static com.commonSocket.application.message.UserLogin.UserLoginResponse parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static com.commonSocket.application.message.UserLogin.UserLoginResponse parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static com.commonSocket.application.message.UserLogin.UserLoginResponse parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static com.commonSocket.application.message.UserLogin.UserLoginResponse parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static com.commonSocket.application.message.UserLogin.UserLoginResponse parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static com.commonSocket.application.message.UserLogin.UserLoginResponse parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static com.commonSocket.application.message.UserLogin.UserLoginResponse parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static com.commonSocket.application.message.UserLogin.UserLoginResponse parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static com.commonSocket.application.message.UserLogin.UserLoginResponse parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static com.commonSocket.application.message.UserLogin.UserLoginResponse parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(com.commonSocket.application.message.UserLogin.UserLoginResponse prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements com.commonSocket.application.message.UserLogin.UserLoginResponseOrBuilder {

            public static final com.google.protobuf.Descriptors.Descriptor
                    getDescriptor() {
                return com.commonSocket.application.message.UserLogin.internal_static_message_UserLoginResponse_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
                    internalGetFieldAccessorTable() {
                return com.commonSocket.application.message.UserLogin.internal_static_message_UserLoginResponse_fieldAccessorTable;
            }

            // Construct using com.powernpc.application.message.UserLogin.UserLoginResponse.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                result_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                info_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                verifyCode_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000004);
                updateAble_ = 0;
                bitField0_ = (bitField0_ & ~0x00000008);
                updateAddress_ = "http://192.168.1.1:80";
                bitField0_ = (bitField0_ & ~0x00000010);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
                    getDescriptorForType() {
                return com.commonSocket.application.message.UserLogin.UserLoginResponse.getDescriptor();
            }

            public com.commonSocket.application.message.UserLogin.UserLoginResponse getDefaultInstanceForType() {
                return com.commonSocket.application.message.UserLogin.UserLoginResponse.getDefaultInstance();
            }

            public com.commonSocket.application.message.UserLogin.UserLoginResponse build() {
                com.commonSocket.application.message.UserLogin.UserLoginResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            private com.commonSocket.application.message.UserLogin.UserLoginResponse buildParsed()
                    throws com.google.protobuf.InvalidProtocolBufferException {
                com.commonSocket.application.message.UserLogin.UserLoginResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(
                            result).asInvalidProtocolBufferException();
                }
                return result;
            }

            public com.commonSocket.application.message.UserLogin.UserLoginResponse buildPartial() {
                com.commonSocket.application.message.UserLogin.UserLoginResponse result = new com.commonSocket.application.message.UserLogin.UserLoginResponse(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.result_ = result_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.info_ = info_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.verifyCode_ = verifyCode_;
                if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
                    to_bitField0_ |= 0x00000008;
                }
                result.updateAble_ = updateAble_;
                if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
                    to_bitField0_ |= 0x00000010;
                }
                result.updateAddress_ = updateAddress_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.commonSocket.application.message.UserLogin.UserLoginResponse) {
                    return mergeFrom((com.commonSocket.application.message.UserLogin.UserLoginResponse) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.commonSocket.application.message.UserLogin.UserLoginResponse other) {
                if (other == com.commonSocket.application.message.UserLogin.UserLoginResponse.getDefaultInstance()) {
                    return this;
                }
                if (other.hasResult()) {
                    setResult(other.getResult());
                }
                if (other.hasInfo()) {
                    setInfo(other.getInfo());
                }
                if (other.hasVerifyCode()) {
                    setVerifyCode(other.getVerifyCode());
                }
                if (other.hasUpdateAble()) {
                    setUpdateAble(other.getUpdateAble());
                }
                if (other.hasUpdateAddress()) {
                    setUpdateAddress(other.getUpdateAddress());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.google.protobuf.UnknownFieldSet.Builder unknownFields
                        = com.google.protobuf.UnknownFieldSet.newBuilder(
                                this.getUnknownFields());
                while (true) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            this.setUnknownFields(unknownFields.build());
                            onChanged();
                            return this;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                this.setUnknownFields(unknownFields.build());
                                onChanged();
                                return this;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            result_ = input.readSInt32();
                            break;
                        }
                        case 18: {
                            bitField0_ |= 0x00000002;
                            info_ = input.readBytes();
                            break;
                        }
                        case 24: {
                            bitField0_ |= 0x00000004;
                            verifyCode_ = input.readUInt64();
                            break;
                        }
                        case 32: {
                            bitField0_ |= 0x00000008;
                            updateAble_ = input.readInt32();
                            break;
                        }
                        case 42: {
                            bitField0_ |= 0x00000010;
                            updateAddress_ = input.readBytes();
                            break;
                        }
                    }
                }
            }

            private int bitField0_;

            // optional sint32 result = 1 [default = 0];
            private int result_;

            public boolean hasResult() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            public int getResult() {
                return result_;
            }

            public Builder setResult(int value) {
                bitField0_ |= 0x00000001;
                result_ = value;
                onChanged();
                return this;
            }

            public Builder clearResult() {
                bitField0_ = (bitField0_ & ~0x00000001);
                result_ = 0;
                onChanged();
                return this;
            }

            // optional string info = 2;
            private java.lang.Object info_ = "";

            public boolean hasInfo() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            public String getInfo() {
                java.lang.Object ref = info_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    info_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            public Builder setInfo(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                info_ = value;
                onChanged();
                return this;
            }

            public Builder clearInfo() {
                bitField0_ = (bitField0_ & ~0x00000002);
                info_ = getDefaultInstance().getInfo();
                onChanged();
                return this;
            }

            void setInfo(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000002;
                info_ = value;
                onChanged();
            }

            // optional uint64 verifyCode = 3;
            private long verifyCode_;

            public boolean hasVerifyCode() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            public long getVerifyCode() {
                return verifyCode_;
            }

            public Builder setVerifyCode(long value) {
                bitField0_ |= 0x00000004;
                verifyCode_ = value;
                onChanged();
                return this;
            }

            public Builder clearVerifyCode() {
                bitField0_ = (bitField0_ & ~0x00000004);
                verifyCode_ = 0L;
                onChanged();
                return this;
            }

            // optional int32 updateAble = 4 [default = 0];
            private int updateAble_;

            public boolean hasUpdateAble() {
                return ((bitField0_ & 0x00000008) == 0x00000008);
            }

            public int getUpdateAble() {
                return updateAble_;
            }

            public Builder setUpdateAble(int value) {
                bitField0_ |= 0x00000008;
                updateAble_ = value;
                onChanged();
                return this;
            }

            public Builder clearUpdateAble() {
                bitField0_ = (bitField0_ & ~0x00000008);
                updateAble_ = 0;
                onChanged();
                return this;
            }

            // optional string updateAddress = 5 [default = "http://192.168.1.1:80"];
            private java.lang.Object updateAddress_ = "http://192.168.1.1:80";

            public boolean hasUpdateAddress() {
                return ((bitField0_ & 0x00000010) == 0x00000010);
            }

            public String getUpdateAddress() {
                java.lang.Object ref = updateAddress_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    updateAddress_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            public Builder setUpdateAddress(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000010;
                updateAddress_ = value;
                onChanged();
                return this;
            }

            public Builder clearUpdateAddress() {
                bitField0_ = (bitField0_ & ~0x00000010);
                updateAddress_ = getDefaultInstance().getUpdateAddress();
                onChanged();
                return this;
            }

            void setUpdateAddress(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000010;
                updateAddress_ = value;
                onChanged();
            }

            // @@protoc_insertion_point(builder_scope:message.UserLoginResponse)
        }

        static {
            defaultInstance = new UserLoginResponse(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:message.UserLoginResponse)
    }

    private static com.google.protobuf.Descriptors.Descriptor internal_static_message_UserLoginRequest_descriptor;
    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_message_UserLoginRequest_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.Descriptor internal_static_message_UserLoginResponse_descriptor;
    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_message_UserLoginResponse_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
            getDescriptor() {
        return descriptor;
    }
    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

    static {
        java.lang.String[] descriptorData = {
            "\n\017UserLogin.proto\022\007message\"\217\002\n\020UserLogin"
            + "Request\022\032\n\010userName\030\001 \002(\t:\010powernpc\022\020\n\010p"
            + "ossWord\030\002 \002(\t\022\023\n\013screenWidth\030\003 \002(\005\022\024\n\014sc"
            + "reenHeight\030\004 \002(\005\022\r\n\005model\030\005 \001(\t\022\r\n\005phone"
            + "\030\006 \001(\t\022\022\n\nsysVersion\030\007 \001(\t\022\023\n\013connectTyp"
            + "e\030\010 \001(\t\022\014\n\004IMEI\030\t \001(\t\022\014\n\004IMSI\030\n \001(\t\022\020\n\010l"
            + "anguage\030\013 \001(\t\022\017\n\007version\030\014 \001(\t\022\r\n\005appId\030"
            + "\r \001(\005\022\r\n\005refId\030\016 \001(\005\"\215\001\n\021UserLoginRespon"
            + "se\022\021\n\006result\030\001 \001(\021:\0010\022\014\n\004info\030\002 \001(\t\022\022\n\nv"
            + "erifyCode\030\003 \001(\004\022\025\n\nupdateAble\030\004 \001(\005:\0010\022,",
            "\n\rupdateAddress\030\005 \001(\t:\025http://192.168.1."
            + "1:80B-\n com.powernpc.application.message"
            + "B\tUserLogin"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner
                = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
            public com.google.protobuf.ExtensionRegistry assignDescriptors(
                    com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                internal_static_message_UserLoginRequest_descriptor
                        = getDescriptor().getMessageTypes().get(0);
                internal_static_message_UserLoginRequest_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                        internal_static_message_UserLoginRequest_descriptor,
                        new java.lang.String[]{"UserName", "PossWord", "ScreenWidth", "ScreenHeight", "Model", "Phone", "SysVersion", "ConnectType", "IMEI", "IMSI", "Language", "Version", "AppId", "RefId",},
                        com.commonSocket.application.message.UserLogin.UserLoginRequest.class,
                        com.commonSocket.application.message.UserLogin.UserLoginRequest.Builder.class);
                internal_static_message_UserLoginResponse_descriptor
                        = getDescriptor().getMessageTypes().get(1);
                internal_static_message_UserLoginResponse_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                        internal_static_message_UserLoginResponse_descriptor,
                        new java.lang.String[]{"Result", "Info", "VerifyCode", "UpdateAble", "UpdateAddress",},
                        com.commonSocket.application.message.UserLogin.UserLoginResponse.class,
                        com.commonSocket.application.message.UserLogin.UserLoginResponse.Builder.class);
                return null;
            }
        };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{}, assigner);
    }

    // @@protoc_insertion_point(outer_class_scope)
}
