// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BattleStart.proto
package com.bw.application.message;

public final class BattleStart {

    private BattleStart() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }

    public interface BattleStartRequestOrBuilder
            extends com.google.protobuf.MessageOrBuilder {

        // required string mailAddress = 1;
        boolean hasMailAddress();

        String getMailAddress();

        // required string defenceMailAddress = 2;
        boolean hasDefenceMailAddress();

        String getDefenceMailAddress();

        // required string start_battle_time = 3;
        boolean hasStartBattleTime();

        String getStartBattleTime();
    }

    public static final class BattleStartRequest extends
            com.google.protobuf.GeneratedMessage
            implements BattleStartRequestOrBuilder {
        // Use BattleStartRequest.newBuilder() to construct.

        private BattleStartRequest(Builder builder) {
            super(builder);
        }

        private BattleStartRequest(boolean noInit) {
        }

        private static final BattleStartRequest defaultInstance;

        public static BattleStartRequest getDefaultInstance() {
            return defaultInstance;
        }

        public BattleStartRequest getDefaultInstanceForType() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
                getDescriptor() {
            return com.bw.application.message.BattleStart.internal_static_message_BattleStartRequest_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
                internalGetFieldAccessorTable() {
            return com.bw.application.message.BattleStart.internal_static_message_BattleStartRequest_fieldAccessorTable;
        }

        private int bitField0_;
        // required string mailAddress = 1;
        public static final int MAILADDRESS_FIELD_NUMBER = 1;
        private java.lang.Object mailAddress_;

        public boolean hasMailAddress() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        public String getMailAddress() {
            java.lang.Object ref = mailAddress_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs
                        = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    mailAddress_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getMailAddressBytes() {
            java.lang.Object ref = mailAddress_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b
                        = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                mailAddress_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // required string defenceMailAddress = 2;
        public static final int DEFENCEMAILADDRESS_FIELD_NUMBER = 2;
        private java.lang.Object defenceMailAddress_;

        public boolean hasDefenceMailAddress() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        public String getDefenceMailAddress() {
            java.lang.Object ref = defenceMailAddress_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs
                        = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    defenceMailAddress_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getDefenceMailAddressBytes() {
            java.lang.Object ref = defenceMailAddress_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b
                        = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                defenceMailAddress_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // required string start_battle_time = 3;
        public static final int START_BATTLE_TIME_FIELD_NUMBER = 3;
        private java.lang.Object startBattleTime_;

        public boolean hasStartBattleTime() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        public String getStartBattleTime() {
            java.lang.Object ref = startBattleTime_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs
                        = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    startBattleTime_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getStartBattleTimeBytes() {
            java.lang.Object ref = startBattleTime_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b
                        = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                startBattleTime_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private void initFields() {
            mailAddress_ = "";
            defenceMailAddress_ = "";
            startBattleTime_ = "";
        }
        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) {
                return isInitialized == 1;
            }

            if (!hasMailAddress()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasDefenceMailAddress()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasStartBattleTime()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(1, getMailAddressBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(2, getDefenceMailAddressBytes());
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeBytes(3, getStartBattleTimeBytes());
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) {
                return size;
            }

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(1, getMailAddressBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, getDefenceMailAddressBytes());
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(3, getStartBattleTimeBytes());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static com.bw.application.message.BattleStart.BattleStartRequest parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static com.bw.application.message.BattleStart.BattleStartRequest parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static com.bw.application.message.BattleStart.BattleStartRequest parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static com.bw.application.message.BattleStart.BattleStartRequest parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static com.bw.application.message.BattleStart.BattleStartRequest parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static com.bw.application.message.BattleStart.BattleStartRequest parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static com.bw.application.message.BattleStart.BattleStartRequest parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static com.bw.application.message.BattleStart.BattleStartRequest parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static com.bw.application.message.BattleStart.BattleStartRequest parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static com.bw.application.message.BattleStart.BattleStartRequest parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(com.bw.application.message.BattleStart.BattleStartRequest prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements com.bw.application.message.BattleStart.BattleStartRequestOrBuilder {

            public static final com.google.protobuf.Descriptors.Descriptor
                    getDescriptor() {
                return com.bw.application.message.BattleStart.internal_static_message_BattleStartRequest_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
                    internalGetFieldAccessorTable() {
                return com.bw.application.message.BattleStart.internal_static_message_BattleStartRequest_fieldAccessorTable;
            }

            // Construct using com.bw.application.message.BattleStart.BattleStartRequest.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                mailAddress_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                defenceMailAddress_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                startBattleTime_ = "";
                bitField0_ = (bitField0_ & ~0x00000004);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
                    getDescriptorForType() {
                return com.bw.application.message.BattleStart.BattleStartRequest.getDescriptor();
            }

            public com.bw.application.message.BattleStart.BattleStartRequest getDefaultInstanceForType() {
                return com.bw.application.message.BattleStart.BattleStartRequest.getDefaultInstance();
            }

            public com.bw.application.message.BattleStart.BattleStartRequest build() {
                com.bw.application.message.BattleStart.BattleStartRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            private com.bw.application.message.BattleStart.BattleStartRequest buildParsed()
                    throws com.google.protobuf.InvalidProtocolBufferException {
                com.bw.application.message.BattleStart.BattleStartRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(
                            result).asInvalidProtocolBufferException();
                }
                return result;
            }

            public com.bw.application.message.BattleStart.BattleStartRequest buildPartial() {
                com.bw.application.message.BattleStart.BattleStartRequest result = new com.bw.application.message.BattleStart.BattleStartRequest(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.mailAddress_ = mailAddress_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.defenceMailAddress_ = defenceMailAddress_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.startBattleTime_ = startBattleTime_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.bw.application.message.BattleStart.BattleStartRequest) {
                    return mergeFrom((com.bw.application.message.BattleStart.BattleStartRequest) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.bw.application.message.BattleStart.BattleStartRequest other) {
                if (other == com.bw.application.message.BattleStart.BattleStartRequest.getDefaultInstance()) {
                    return this;
                }
                if (other.hasMailAddress()) {
                    setMailAddress(other.getMailAddress());
                }
                if (other.hasDefenceMailAddress()) {
                    setDefenceMailAddress(other.getDefenceMailAddress());
                }
                if (other.hasStartBattleTime()) {
                    setStartBattleTime(other.getStartBattleTime());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasMailAddress()) {

                    return false;
                }
                if (!hasDefenceMailAddress()) {

                    return false;
                }
                if (!hasStartBattleTime()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.google.protobuf.UnknownFieldSet.Builder unknownFields
                        = com.google.protobuf.UnknownFieldSet.newBuilder(
                                this.getUnknownFields());
                while (true) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            this.setUnknownFields(unknownFields.build());
                            onChanged();
                            return this;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                this.setUnknownFields(unknownFields.build());
                                onChanged();
                                return this;
                            }
                            break;
                        }
                        case 10: {
                            bitField0_ |= 0x00000001;
                            mailAddress_ = input.readBytes();
                            break;
                        }
                        case 18: {
                            bitField0_ |= 0x00000002;
                            defenceMailAddress_ = input.readBytes();
                            break;
                        }
                        case 26: {
                            bitField0_ |= 0x00000004;
                            startBattleTime_ = input.readBytes();
                            break;
                        }
                    }
                }
            }

            private int bitField0_;

            // required string mailAddress = 1;
            private java.lang.Object mailAddress_ = "";

            public boolean hasMailAddress() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            public String getMailAddress() {
                java.lang.Object ref = mailAddress_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    mailAddress_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            public Builder setMailAddress(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                mailAddress_ = value;
                onChanged();
                return this;
            }

            public Builder clearMailAddress() {
                bitField0_ = (bitField0_ & ~0x00000001);
                mailAddress_ = getDefaultInstance().getMailAddress();
                onChanged();
                return this;
            }

            void setMailAddress(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000001;
                mailAddress_ = value;
                onChanged();
            }

            // required string defenceMailAddress = 2;
            private java.lang.Object defenceMailAddress_ = "";

            public boolean hasDefenceMailAddress() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            public String getDefenceMailAddress() {
                java.lang.Object ref = defenceMailAddress_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    defenceMailAddress_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            public Builder setDefenceMailAddress(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                defenceMailAddress_ = value;
                onChanged();
                return this;
            }

            public Builder clearDefenceMailAddress() {
                bitField0_ = (bitField0_ & ~0x00000002);
                defenceMailAddress_ = getDefaultInstance().getDefenceMailAddress();
                onChanged();
                return this;
            }

            void setDefenceMailAddress(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000002;
                defenceMailAddress_ = value;
                onChanged();
            }

            // required string start_battle_time = 3;
            private java.lang.Object startBattleTime_ = "";

            public boolean hasStartBattleTime() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            public String getStartBattleTime() {
                java.lang.Object ref = startBattleTime_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    startBattleTime_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            public Builder setStartBattleTime(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                startBattleTime_ = value;
                onChanged();
                return this;
            }

            public Builder clearStartBattleTime() {
                bitField0_ = (bitField0_ & ~0x00000004);
                startBattleTime_ = getDefaultInstance().getStartBattleTime();
                onChanged();
                return this;
            }

            void setStartBattleTime(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000004;
                startBattleTime_ = value;
                onChanged();
            }

            // @@protoc_insertion_point(builder_scope:message.BattleStartRequest)
        }

        static {
            defaultInstance = new BattleStartRequest(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:message.BattleStartRequest)
    }

    public interface BattleStartResponseOrBuilder
            extends com.google.protobuf.MessageOrBuilder {

        // optional sint32 result = 1 [default = 0];
        boolean hasResult();

        int getResult();

        // optional string info = 2;
        boolean hasInfo();

        String getInfo();

        // optional int64 battleId = 3;
        boolean hasBattleId();

        long getBattleId();

        // optional uint64 verifyCode = 4;
        boolean hasVerifyCode();

        long getVerifyCode();
    }

    public static final class BattleStartResponse extends
            com.google.protobuf.GeneratedMessage
            implements BattleStartResponseOrBuilder {
        // Use BattleStartResponse.newBuilder() to construct.

        private BattleStartResponse(Builder builder) {
            super(builder);
        }

        private BattleStartResponse(boolean noInit) {
        }

        private static final BattleStartResponse defaultInstance;

        public static BattleStartResponse getDefaultInstance() {
            return defaultInstance;
        }

        public BattleStartResponse getDefaultInstanceForType() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
                getDescriptor() {
            return com.bw.application.message.BattleStart.internal_static_message_BattleStartResponse_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
                internalGetFieldAccessorTable() {
            return com.bw.application.message.BattleStart.internal_static_message_BattleStartResponse_fieldAccessorTable;
        }

        private int bitField0_;
        // optional sint32 result = 1 [default = 0];
        public static final int RESULT_FIELD_NUMBER = 1;
        private int result_;

        public boolean hasResult() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        public int getResult() {
            return result_;
        }

        // optional string info = 2;
        public static final int INFO_FIELD_NUMBER = 2;
        private java.lang.Object info_;

        public boolean hasInfo() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        public String getInfo() {
            java.lang.Object ref = info_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs
                        = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    info_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getInfoBytes() {
            java.lang.Object ref = info_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b
                        = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                info_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // optional int64 battleId = 3;
        public static final int BATTLEID_FIELD_NUMBER = 3;
        private long battleId_;

        public boolean hasBattleId() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        public long getBattleId() {
            return battleId_;
        }

        // optional uint64 verifyCode = 4;
        public static final int VERIFYCODE_FIELD_NUMBER = 4;
        private long verifyCode_;

        public boolean hasVerifyCode() {
            return ((bitField0_ & 0x00000008) == 0x00000008);
        }

        public long getVerifyCode() {
            return verifyCode_;
        }

        private void initFields() {
            result_ = 0;
            info_ = "";
            battleId_ = 0L;
            verifyCode_ = 0L;
        }
        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) {
                return isInitialized == 1;
            }

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeSInt32(1, result_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(2, getInfoBytes());
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeInt64(3, battleId_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                output.writeUInt64(4, verifyCode_);
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) {
                return size;
            }

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeSInt32Size(1, result_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, getInfoBytes());
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(3, battleId_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(4, verifyCode_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static com.bw.application.message.BattleStart.BattleStartResponse parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static com.bw.application.message.BattleStart.BattleStartResponse parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static com.bw.application.message.BattleStart.BattleStartResponse parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static com.bw.application.message.BattleStart.BattleStartResponse parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static com.bw.application.message.BattleStart.BattleStartResponse parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static com.bw.application.message.BattleStart.BattleStartResponse parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static com.bw.application.message.BattleStart.BattleStartResponse parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static com.bw.application.message.BattleStart.BattleStartResponse parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static com.bw.application.message.BattleStart.BattleStartResponse parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static com.bw.application.message.BattleStart.BattleStartResponse parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(com.bw.application.message.BattleStart.BattleStartResponse prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements com.bw.application.message.BattleStart.BattleStartResponseOrBuilder {

            public static final com.google.protobuf.Descriptors.Descriptor
                    getDescriptor() {
                return com.bw.application.message.BattleStart.internal_static_message_BattleStartResponse_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
                    internalGetFieldAccessorTable() {
                return com.bw.application.message.BattleStart.internal_static_message_BattleStartResponse_fieldAccessorTable;
            }

            // Construct using com.bw.application.message.BattleStart.BattleStartResponse.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                result_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                info_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                battleId_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000004);
                verifyCode_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000008);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
                    getDescriptorForType() {
                return com.bw.application.message.BattleStart.BattleStartResponse.getDescriptor();
            }

            public com.bw.application.message.BattleStart.BattleStartResponse getDefaultInstanceForType() {
                return com.bw.application.message.BattleStart.BattleStartResponse.getDefaultInstance();
            }

            public com.bw.application.message.BattleStart.BattleStartResponse build() {
                com.bw.application.message.BattleStart.BattleStartResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            private com.bw.application.message.BattleStart.BattleStartResponse buildParsed()
                    throws com.google.protobuf.InvalidProtocolBufferException {
                com.bw.application.message.BattleStart.BattleStartResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(
                            result).asInvalidProtocolBufferException();
                }
                return result;
            }

            public com.bw.application.message.BattleStart.BattleStartResponse buildPartial() {
                com.bw.application.message.BattleStart.BattleStartResponse result = new com.bw.application.message.BattleStart.BattleStartResponse(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.result_ = result_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.info_ = info_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.battleId_ = battleId_;
                if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
                    to_bitField0_ |= 0x00000008;
                }
                result.verifyCode_ = verifyCode_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.bw.application.message.BattleStart.BattleStartResponse) {
                    return mergeFrom((com.bw.application.message.BattleStart.BattleStartResponse) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.bw.application.message.BattleStart.BattleStartResponse other) {
                if (other == com.bw.application.message.BattleStart.BattleStartResponse.getDefaultInstance()) {
                    return this;
                }
                if (other.hasResult()) {
                    setResult(other.getResult());
                }
                if (other.hasInfo()) {
                    setInfo(other.getInfo());
                }
                if (other.hasBattleId()) {
                    setBattleId(other.getBattleId());
                }
                if (other.hasVerifyCode()) {
                    setVerifyCode(other.getVerifyCode());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.google.protobuf.UnknownFieldSet.Builder unknownFields
                        = com.google.protobuf.UnknownFieldSet.newBuilder(
                                this.getUnknownFields());
                while (true) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            this.setUnknownFields(unknownFields.build());
                            onChanged();
                            return this;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                this.setUnknownFields(unknownFields.build());
                                onChanged();
                                return this;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            result_ = input.readSInt32();
                            break;
                        }
                        case 18: {
                            bitField0_ |= 0x00000002;
                            info_ = input.readBytes();
                            break;
                        }
                        case 24: {
                            bitField0_ |= 0x00000004;
                            battleId_ = input.readInt64();
                            break;
                        }
                        case 32: {
                            bitField0_ |= 0x00000008;
                            verifyCode_ = input.readUInt64();
                            break;
                        }
                    }
                }
            }

            private int bitField0_;

            // optional sint32 result = 1 [default = 0];
            private int result_;

            public boolean hasResult() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            public int getResult() {
                return result_;
            }

            public Builder setResult(int value) {
                bitField0_ |= 0x00000001;
                result_ = value;
                onChanged();
                return this;
            }

            public Builder clearResult() {
                bitField0_ = (bitField0_ & ~0x00000001);
                result_ = 0;
                onChanged();
                return this;
            }

            // optional string info = 2;
            private java.lang.Object info_ = "";

            public boolean hasInfo() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            public String getInfo() {
                java.lang.Object ref = info_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    info_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            public Builder setInfo(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                info_ = value;
                onChanged();
                return this;
            }

            public Builder clearInfo() {
                bitField0_ = (bitField0_ & ~0x00000002);
                info_ = getDefaultInstance().getInfo();
                onChanged();
                return this;
            }

            void setInfo(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000002;
                info_ = value;
                onChanged();
            }

            // optional int64 battleId = 3;
            private long battleId_;

            public boolean hasBattleId() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            public long getBattleId() {
                return battleId_;
            }

            public Builder setBattleId(long value) {
                bitField0_ |= 0x00000004;
                battleId_ = value;
                onChanged();
                return this;
            }

            public Builder clearBattleId() {
                bitField0_ = (bitField0_ & ~0x00000004);
                battleId_ = 0L;
                onChanged();
                return this;
            }

            // optional uint64 verifyCode = 4;
            private long verifyCode_;

            public boolean hasVerifyCode() {
                return ((bitField0_ & 0x00000008) == 0x00000008);
            }

            public long getVerifyCode() {
                return verifyCode_;
            }

            public Builder setVerifyCode(long value) {
                bitField0_ |= 0x00000008;
                verifyCode_ = value;
                onChanged();
                return this;
            }

            public Builder clearVerifyCode() {
                bitField0_ = (bitField0_ & ~0x00000008);
                verifyCode_ = 0L;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:message.BattleStartResponse)
        }

        static {
            defaultInstance = new BattleStartResponse(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:message.BattleStartResponse)
    }

    private static com.google.protobuf.Descriptors.Descriptor internal_static_message_BattleStartRequest_descriptor;
    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_message_BattleStartRequest_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.Descriptor internal_static_message_BattleStartResponse_descriptor;
    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_message_BattleStartResponse_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
            getDescriptor() {
        return descriptor;
    }
    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

    static {
        java.lang.String[] descriptorData = {
            "\n\021BattleStart.proto\022\007message\"`\n\022BattleSt"
            + "artRequest\022\023\n\013mailAddress\030\001 \002(\t\022\032\n\022defen"
            + "ceMailAddress\030\002 \002(\t\022\031\n\021start_battle_time"
            + "\030\003 \002(\t\"\\\n\023BattleStartResponse\022\021\n\006result\030"
            + "\001 \001(\021:\0010\022\014\n\004info\030\002 \001(\t\022\020\n\010battleId\030\003 \001(\003"
            + "\022\022\n\nverifyCode\030\004 \001(\004B)\n\032com.bw.applicati"
            + "on.messageB\013BattleStart"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner
                = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
            public com.google.protobuf.ExtensionRegistry assignDescriptors(
                    com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                internal_static_message_BattleStartRequest_descriptor
                        = getDescriptor().getMessageTypes().get(0);
                internal_static_message_BattleStartRequest_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                        internal_static_message_BattleStartRequest_descriptor,
                        new java.lang.String[]{"MailAddress", "DefenceMailAddress", "StartBattleTime",},
                        com.bw.application.message.BattleStart.BattleStartRequest.class,
                        com.bw.application.message.BattleStart.BattleStartRequest.Builder.class);
                internal_static_message_BattleStartResponse_descriptor
                        = getDescriptor().getMessageTypes().get(1);
                internal_static_message_BattleStartResponse_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                        internal_static_message_BattleStartResponse_descriptor,
                        new java.lang.String[]{"Result", "Info", "BattleId", "VerifyCode",},
                        com.bw.application.message.BattleStart.BattleStartResponse.class,
                        com.bw.application.message.BattleStart.BattleStartResponse.Builder.class);
                return null;
            }
        };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{}, assigner);
    }

    // @@protoc_insertion_point(outer_class_scope)
}
