// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CancleBattle.proto
package com.bw.application.message;

public final class CancleBattle {

    private CancleBattle() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }

    public interface CancleBattleRequestOrBuilder
            extends com.google.protobuf.MessageOrBuilder {

        // required string mailAddress = 1;
        boolean hasMailAddress();

        String getMailAddress();
    }

    public static final class CancleBattleRequest extends
            com.google.protobuf.GeneratedMessage
            implements CancleBattleRequestOrBuilder {
        // Use CancleBattleRequest.newBuilder() to construct.

        private CancleBattleRequest(Builder builder) {
            super(builder);
        }

        private CancleBattleRequest(boolean noInit) {
        }

        private static final CancleBattleRequest defaultInstance;

        public static CancleBattleRequest getDefaultInstance() {
            return defaultInstance;
        }

        public CancleBattleRequest getDefaultInstanceForType() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
                getDescriptor() {
            return com.bw.application.message.CancleBattle.internal_static_message_CancleBattleRequest_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
                internalGetFieldAccessorTable() {
            return com.bw.application.message.CancleBattle.internal_static_message_CancleBattleRequest_fieldAccessorTable;
        }

        private int bitField0_;
        // required string mailAddress = 1;
        public static final int MAILADDRESS_FIELD_NUMBER = 1;
        private java.lang.Object mailAddress_;

        public boolean hasMailAddress() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        public String getMailAddress() {
            java.lang.Object ref = mailAddress_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs
                        = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    mailAddress_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getMailAddressBytes() {
            java.lang.Object ref = mailAddress_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b
                        = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                mailAddress_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private void initFields() {
            mailAddress_ = "";
        }
        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) {
                return isInitialized == 1;
            }

            if (!hasMailAddress()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(1, getMailAddressBytes());
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) {
                return size;
            }

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(1, getMailAddressBytes());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static com.bw.application.message.CancleBattle.CancleBattleRequest parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static com.bw.application.message.CancleBattle.CancleBattleRequest parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static com.bw.application.message.CancleBattle.CancleBattleRequest parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static com.bw.application.message.CancleBattle.CancleBattleRequest parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static com.bw.application.message.CancleBattle.CancleBattleRequest parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static com.bw.application.message.CancleBattle.CancleBattleRequest parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static com.bw.application.message.CancleBattle.CancleBattleRequest parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static com.bw.application.message.CancleBattle.CancleBattleRequest parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static com.bw.application.message.CancleBattle.CancleBattleRequest parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static com.bw.application.message.CancleBattle.CancleBattleRequest parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(com.bw.application.message.CancleBattle.CancleBattleRequest prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements com.bw.application.message.CancleBattle.CancleBattleRequestOrBuilder {

            public static final com.google.protobuf.Descriptors.Descriptor
                    getDescriptor() {
                return com.bw.application.message.CancleBattle.internal_static_message_CancleBattleRequest_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
                    internalGetFieldAccessorTable() {
                return com.bw.application.message.CancleBattle.internal_static_message_CancleBattleRequest_fieldAccessorTable;
            }

            // Construct using com.bw.application.message.CancleBattle.CancleBattleRequest.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                mailAddress_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
                    getDescriptorForType() {
                return com.bw.application.message.CancleBattle.CancleBattleRequest.getDescriptor();
            }

            public com.bw.application.message.CancleBattle.CancleBattleRequest getDefaultInstanceForType() {
                return com.bw.application.message.CancleBattle.CancleBattleRequest.getDefaultInstance();
            }

            public com.bw.application.message.CancleBattle.CancleBattleRequest build() {
                com.bw.application.message.CancleBattle.CancleBattleRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            private com.bw.application.message.CancleBattle.CancleBattleRequest buildParsed()
                    throws com.google.protobuf.InvalidProtocolBufferException {
                com.bw.application.message.CancleBattle.CancleBattleRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(
                            result).asInvalidProtocolBufferException();
                }
                return result;
            }

            public com.bw.application.message.CancleBattle.CancleBattleRequest buildPartial() {
                com.bw.application.message.CancleBattle.CancleBattleRequest result = new com.bw.application.message.CancleBattle.CancleBattleRequest(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.mailAddress_ = mailAddress_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.bw.application.message.CancleBattle.CancleBattleRequest) {
                    return mergeFrom((com.bw.application.message.CancleBattle.CancleBattleRequest) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.bw.application.message.CancleBattle.CancleBattleRequest other) {
                if (other == com.bw.application.message.CancleBattle.CancleBattleRequest.getDefaultInstance()) {
                    return this;
                }
                if (other.hasMailAddress()) {
                    setMailAddress(other.getMailAddress());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasMailAddress()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.google.protobuf.UnknownFieldSet.Builder unknownFields
                        = com.google.protobuf.UnknownFieldSet.newBuilder(
                                this.getUnknownFields());
                while (true) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            this.setUnknownFields(unknownFields.build());
                            onChanged();
                            return this;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                this.setUnknownFields(unknownFields.build());
                                onChanged();
                                return this;
                            }
                            break;
                        }
                        case 10: {
                            bitField0_ |= 0x00000001;
                            mailAddress_ = input.readBytes();
                            break;
                        }
                    }
                }
            }

            private int bitField0_;

            // required string mailAddress = 1;
            private java.lang.Object mailAddress_ = "";

            public boolean hasMailAddress() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            public String getMailAddress() {
                java.lang.Object ref = mailAddress_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    mailAddress_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            public Builder setMailAddress(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                mailAddress_ = value;
                onChanged();
                return this;
            }

            public Builder clearMailAddress() {
                bitField0_ = (bitField0_ & ~0x00000001);
                mailAddress_ = getDefaultInstance().getMailAddress();
                onChanged();
                return this;
            }

            void setMailAddress(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000001;
                mailAddress_ = value;
                onChanged();
            }

            // @@protoc_insertion_point(builder_scope:message.CancleBattleRequest)
        }

        static {
            defaultInstance = new CancleBattleRequest(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:message.CancleBattleRequest)
    }

    public interface CancleBattleResponseOrBuilder
            extends com.google.protobuf.MessageOrBuilder {

        // optional sint32 result = 1 [default = 0];
        boolean hasResult();

        int getResult();

        // optional string info = 2;
        boolean hasInfo();

        String getInfo();
    }

    public static final class CancleBattleResponse extends
            com.google.protobuf.GeneratedMessage
            implements CancleBattleResponseOrBuilder {
        // Use CancleBattleResponse.newBuilder() to construct.

        private CancleBattleResponse(Builder builder) {
            super(builder);
        }

        private CancleBattleResponse(boolean noInit) {
        }

        private static final CancleBattleResponse defaultInstance;

        public static CancleBattleResponse getDefaultInstance() {
            return defaultInstance;
        }

        public CancleBattleResponse getDefaultInstanceForType() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
                getDescriptor() {
            return com.bw.application.message.CancleBattle.internal_static_message_CancleBattleResponse_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
                internalGetFieldAccessorTable() {
            return com.bw.application.message.CancleBattle.internal_static_message_CancleBattleResponse_fieldAccessorTable;
        }

        private int bitField0_;
        // optional sint32 result = 1 [default = 0];
        public static final int RESULT_FIELD_NUMBER = 1;
        private int result_;

        public boolean hasResult() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        public int getResult() {
            return result_;
        }

        // optional string info = 2;
        public static final int INFO_FIELD_NUMBER = 2;
        private java.lang.Object info_;

        public boolean hasInfo() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        public String getInfo() {
            java.lang.Object ref = info_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs
                        = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    info_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getInfoBytes() {
            java.lang.Object ref = info_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b
                        = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                info_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private void initFields() {
            result_ = 0;
            info_ = "";
        }
        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) {
                return isInitialized == 1;
            }

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeSInt32(1, result_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(2, getInfoBytes());
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) {
                return size;
            }

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeSInt32Size(1, result_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, getInfoBytes());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static com.bw.application.message.CancleBattle.CancleBattleResponse parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static com.bw.application.message.CancleBattle.CancleBattleResponse parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static com.bw.application.message.CancleBattle.CancleBattleResponse parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static com.bw.application.message.CancleBattle.CancleBattleResponse parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static com.bw.application.message.CancleBattle.CancleBattleResponse parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static com.bw.application.message.CancleBattle.CancleBattleResponse parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static com.bw.application.message.CancleBattle.CancleBattleResponse parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static com.bw.application.message.CancleBattle.CancleBattleResponse parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static com.bw.application.message.CancleBattle.CancleBattleResponse parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static com.bw.application.message.CancleBattle.CancleBattleResponse parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(com.bw.application.message.CancleBattle.CancleBattleResponse prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements com.bw.application.message.CancleBattle.CancleBattleResponseOrBuilder {

            public static final com.google.protobuf.Descriptors.Descriptor
                    getDescriptor() {
                return com.bw.application.message.CancleBattle.internal_static_message_CancleBattleResponse_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
                    internalGetFieldAccessorTable() {
                return com.bw.application.message.CancleBattle.internal_static_message_CancleBattleResponse_fieldAccessorTable;
            }

            // Construct using com.bw.application.message.CancleBattle.CancleBattleResponse.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                result_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                info_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
                    getDescriptorForType() {
                return com.bw.application.message.CancleBattle.CancleBattleResponse.getDescriptor();
            }

            public com.bw.application.message.CancleBattle.CancleBattleResponse getDefaultInstanceForType() {
                return com.bw.application.message.CancleBattle.CancleBattleResponse.getDefaultInstance();
            }

            public com.bw.application.message.CancleBattle.CancleBattleResponse build() {
                com.bw.application.message.CancleBattle.CancleBattleResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            private com.bw.application.message.CancleBattle.CancleBattleResponse buildParsed()
                    throws com.google.protobuf.InvalidProtocolBufferException {
                com.bw.application.message.CancleBattle.CancleBattleResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(
                            result).asInvalidProtocolBufferException();
                }
                return result;
            }

            public com.bw.application.message.CancleBattle.CancleBattleResponse buildPartial() {
                com.bw.application.message.CancleBattle.CancleBattleResponse result = new com.bw.application.message.CancleBattle.CancleBattleResponse(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.result_ = result_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.info_ = info_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.bw.application.message.CancleBattle.CancleBattleResponse) {
                    return mergeFrom((com.bw.application.message.CancleBattle.CancleBattleResponse) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.bw.application.message.CancleBattle.CancleBattleResponse other) {
                if (other == com.bw.application.message.CancleBattle.CancleBattleResponse.getDefaultInstance()) {
                    return this;
                }
                if (other.hasResult()) {
                    setResult(other.getResult());
                }
                if (other.hasInfo()) {
                    setInfo(other.getInfo());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.google.protobuf.UnknownFieldSet.Builder unknownFields
                        = com.google.protobuf.UnknownFieldSet.newBuilder(
                                this.getUnknownFields());
                while (true) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            this.setUnknownFields(unknownFields.build());
                            onChanged();
                            return this;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                this.setUnknownFields(unknownFields.build());
                                onChanged();
                                return this;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            result_ = input.readSInt32();
                            break;
                        }
                        case 18: {
                            bitField0_ |= 0x00000002;
                            info_ = input.readBytes();
                            break;
                        }
                    }
                }
            }

            private int bitField0_;

            // optional sint32 result = 1 [default = 0];
            private int result_;

            public boolean hasResult() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            public int getResult() {
                return result_;
            }

            public Builder setResult(int value) {
                bitField0_ |= 0x00000001;
                result_ = value;
                onChanged();
                return this;
            }

            public Builder clearResult() {
                bitField0_ = (bitField0_ & ~0x00000001);
                result_ = 0;
                onChanged();
                return this;
            }

            // optional string info = 2;
            private java.lang.Object info_ = "";

            public boolean hasInfo() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            public String getInfo() {
                java.lang.Object ref = info_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    info_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            public Builder setInfo(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                info_ = value;
                onChanged();
                return this;
            }

            public Builder clearInfo() {
                bitField0_ = (bitField0_ & ~0x00000002);
                info_ = getDefaultInstance().getInfo();
                onChanged();
                return this;
            }

            void setInfo(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000002;
                info_ = value;
                onChanged();
            }

            // @@protoc_insertion_point(builder_scope:message.CancleBattleResponse)
        }

        static {
            defaultInstance = new CancleBattleResponse(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:message.CancleBattleResponse)
    }

    private static com.google.protobuf.Descriptors.Descriptor internal_static_message_CancleBattleRequest_descriptor;
    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_message_CancleBattleRequest_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.Descriptor internal_static_message_CancleBattleResponse_descriptor;
    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_message_CancleBattleResponse_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
            getDescriptor() {
        return descriptor;
    }
    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

    static {
        java.lang.String[] descriptorData = {
            "\n\022CancleBattle.proto\022\007message\"*\n\023CancleB"
            + "attleRequest\022\023\n\013mailAddress\030\001 \002(\t\"7\n\024Can"
            + "cleBattleResponse\022\021\n\006result\030\001 \001(\021:\0010\022\014\n\004"
            + "info\030\002 \001(\tB*\n\032com.bw.application.message"
            + "B\014CancleBattle"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner
                = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
            public com.google.protobuf.ExtensionRegistry assignDescriptors(
                    com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                internal_static_message_CancleBattleRequest_descriptor
                        = getDescriptor().getMessageTypes().get(0);
                internal_static_message_CancleBattleRequest_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                        internal_static_message_CancleBattleRequest_descriptor,
                        new java.lang.String[]{"MailAddress",},
                        com.bw.application.message.CancleBattle.CancleBattleRequest.class,
                        com.bw.application.message.CancleBattle.CancleBattleRequest.Builder.class);
                internal_static_message_CancleBattleResponse_descriptor
                        = getDescriptor().getMessageTypes().get(1);
                internal_static_message_CancleBattleResponse_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                        internal_static_message_CancleBattleResponse_descriptor,
                        new java.lang.String[]{"Result", "Info",},
                        com.bw.application.message.CancleBattle.CancleBattleResponse.class,
                        com.bw.application.message.CancleBattle.CancleBattleResponse.Builder.class);
                return null;
            }
        };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{}, assigner);
    }

    // @@protoc_insertion_point(outer_class_scope)
}
