// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProduceSoldierMessage.proto
package com.bw.application.message;

public final class ProduceSoldierMessage {

    private ProduceSoldierMessage() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }

    public interface ProduceSoldiersRequestOrBuilder
            extends com.google.protobuf.MessageOrBuilder {

        // required string mailAddress = 1;
        boolean hasMailAddress();

        String getMailAddress();

        // repeated .message.ProduceSoldiersRequest.ProduceSoldiers soldiersList = 2;
        java.util.List<com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers>
                getSoldiersListList();

        com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers getSoldiersList(int index);

        int getSoldiersListCount();

        java.util.List<? extends com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiersOrBuilder>
                getSoldiersListOrBuilderList();

        com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiersOrBuilder getSoldiersListOrBuilder(
                int index);

        // optional int32 create_state = 3;
        boolean hasCreateState();

        int getCreateState();
    }

    public static final class ProduceSoldiersRequest extends
            com.google.protobuf.GeneratedMessage
            implements ProduceSoldiersRequestOrBuilder {
        // Use ProduceSoldiersRequest.newBuilder() to construct.

        private ProduceSoldiersRequest(Builder builder) {
            super(builder);
        }

        private ProduceSoldiersRequest(boolean noInit) {
        }

        private static final ProduceSoldiersRequest defaultInstance;

        public static ProduceSoldiersRequest getDefaultInstance() {
            return defaultInstance;
        }

        public ProduceSoldiersRequest getDefaultInstanceForType() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
                getDescriptor() {
            return com.bw.application.message.ProduceSoldierMessage.internal_static_message_ProduceSoldiersRequest_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
                internalGetFieldAccessorTable() {
            return com.bw.application.message.ProduceSoldierMessage.internal_static_message_ProduceSoldiersRequest_fieldAccessorTable;
        }

        public interface ProduceSoldiersOrBuilder
                extends com.google.protobuf.MessageOrBuilder {

            // optional int32 character_id = 1;
            boolean hasCharacterId();

            int getCharacterId();

            // optional int32 character_level = 2;
            boolean hasCharacterLevel();

            int getCharacterLevel();

            // optional int32 produce_count = 3;
            boolean hasProduceCount();

            int getProduceCount();

            // optional int32 index = 4;
            boolean hasIndex();

            int getIndex();

            // optional int32 uuid = 5;
            boolean hasUuid();

            int getUuid();
        }

        public static final class ProduceSoldiers extends
                com.google.protobuf.GeneratedMessage
                implements ProduceSoldiersOrBuilder {
            // Use ProduceSoldiers.newBuilder() to construct.

            private ProduceSoldiers(Builder builder) {
                super(builder);
            }

            private ProduceSoldiers(boolean noInit) {
            }

            private static final ProduceSoldiers defaultInstance;

            public static ProduceSoldiers getDefaultInstance() {
                return defaultInstance;
            }

            public ProduceSoldiers getDefaultInstanceForType() {
                return defaultInstance;
            }

            public static final com.google.protobuf.Descriptors.Descriptor
                    getDescriptor() {
                return com.bw.application.message.ProduceSoldierMessage.internal_static_message_ProduceSoldiersRequest_ProduceSoldiers_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
                    internalGetFieldAccessorTable() {
                return com.bw.application.message.ProduceSoldierMessage.internal_static_message_ProduceSoldiersRequest_ProduceSoldiers_fieldAccessorTable;
            }

            private int bitField0_;
            // optional int32 character_id = 1;
            public static final int CHARACTER_ID_FIELD_NUMBER = 1;
            private int characterId_;

            public boolean hasCharacterId() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            public int getCharacterId() {
                return characterId_;
            }

            // optional int32 character_level = 2;
            public static final int CHARACTER_LEVEL_FIELD_NUMBER = 2;
            private int characterLevel_;

            public boolean hasCharacterLevel() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            public int getCharacterLevel() {
                return characterLevel_;
            }

            // optional int32 produce_count = 3;
            public static final int PRODUCE_COUNT_FIELD_NUMBER = 3;
            private int produceCount_;

            public boolean hasProduceCount() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            public int getProduceCount() {
                return produceCount_;
            }

            // optional int32 index = 4;
            public static final int INDEX_FIELD_NUMBER = 4;
            private int index_;

            public boolean hasIndex() {
                return ((bitField0_ & 0x00000008) == 0x00000008);
            }

            public int getIndex() {
                return index_;
            }

            // optional int32 uuid = 5;
            public static final int UUID_FIELD_NUMBER = 5;
            private int uuid_;

            public boolean hasUuid() {
                return ((bitField0_ & 0x00000010) == 0x00000010);
            }

            public int getUuid() {
                return uuid_;
            }

            private void initFields() {
                characterId_ = 0;
                characterLevel_ = 0;
                produceCount_ = 0;
                index_ = 0;
                uuid_ = 0;
            }
            private byte memoizedIsInitialized = -1;

            public final boolean isInitialized() {
                byte isInitialized = memoizedIsInitialized;
                if (isInitialized != -1) {
                    return isInitialized == 1;
                }

                memoizedIsInitialized = 1;
                return true;
            }

            public void writeTo(com.google.protobuf.CodedOutputStream output)
                    throws java.io.IOException {
                getSerializedSize();
                if (((bitField0_ & 0x00000001) == 0x00000001)) {
                    output.writeInt32(1, characterId_);
                }
                if (((bitField0_ & 0x00000002) == 0x00000002)) {
                    output.writeInt32(2, characterLevel_);
                }
                if (((bitField0_ & 0x00000004) == 0x00000004)) {
                    output.writeInt32(3, produceCount_);
                }
                if (((bitField0_ & 0x00000008) == 0x00000008)) {
                    output.writeInt32(4, index_);
                }
                if (((bitField0_ & 0x00000010) == 0x00000010)) {
                    output.writeInt32(5, uuid_);
                }
                getUnknownFields().writeTo(output);
            }

            private int memoizedSerializedSize = -1;

            public int getSerializedSize() {
                int size = memoizedSerializedSize;
                if (size != -1) {
                    return size;
                }

                size = 0;
                if (((bitField0_ & 0x00000001) == 0x00000001)) {
                    size += com.google.protobuf.CodedOutputStream
                            .computeInt32Size(1, characterId_);
                }
                if (((bitField0_ & 0x00000002) == 0x00000002)) {
                    size += com.google.protobuf.CodedOutputStream
                            .computeInt32Size(2, characterLevel_);
                }
                if (((bitField0_ & 0x00000004) == 0x00000004)) {
                    size += com.google.protobuf.CodedOutputStream
                            .computeInt32Size(3, produceCount_);
                }
                if (((bitField0_ & 0x00000008) == 0x00000008)) {
                    size += com.google.protobuf.CodedOutputStream
                            .computeInt32Size(4, index_);
                }
                if (((bitField0_ & 0x00000010) == 0x00000010)) {
                    size += com.google.protobuf.CodedOutputStream
                            .computeInt32Size(5, uuid_);
                }
                size += getUnknownFields().getSerializedSize();
                memoizedSerializedSize = size;
                return size;
            }

            private static final long serialVersionUID = 0L;

            @java.lang.Override
            protected java.lang.Object writeReplace()
                    throws java.io.ObjectStreamException {
                return super.writeReplace();
            }

            public static com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers parseFrom(
                    com.google.protobuf.ByteString data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return newBuilder().mergeFrom(data).buildParsed();
            }

            public static com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers parseFrom(
                    com.google.protobuf.ByteString data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return newBuilder().mergeFrom(data, extensionRegistry)
                        .buildParsed();
            }

            public static com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers parseFrom(byte[] data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return newBuilder().mergeFrom(data).buildParsed();
            }

            public static com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers parseFrom(
                    byte[] data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return newBuilder().mergeFrom(data, extensionRegistry)
                        .buildParsed();
            }

            public static com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers parseFrom(java.io.InputStream input)
                    throws java.io.IOException {
                return newBuilder().mergeFrom(input).buildParsed();
            }

            public static com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers parseFrom(
                    java.io.InputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                return newBuilder().mergeFrom(input, extensionRegistry)
                        .buildParsed();
            }

            public static com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers parseDelimitedFrom(java.io.InputStream input)
                    throws java.io.IOException {
                Builder builder = newBuilder();
                if (builder.mergeDelimitedFrom(input)) {
                    return builder.buildParsed();
                } else {
                    return null;
                }
            }

            public static com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers parseDelimitedFrom(
                    java.io.InputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                Builder builder = newBuilder();
                if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
                    return builder.buildParsed();
                } else {
                    return null;
                }
            }

            public static com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers parseFrom(
                    com.google.protobuf.CodedInputStream input)
                    throws java.io.IOException {
                return newBuilder().mergeFrom(input).buildParsed();
            }

            public static com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers parseFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                return newBuilder().mergeFrom(input, extensionRegistry)
                        .buildParsed();
            }

            public static Builder newBuilder() {
                return Builder.create();
            }

            public Builder newBuilderForType() {
                return newBuilder();
            }

            public static Builder newBuilder(com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers prototype) {
                return newBuilder().mergeFrom(prototype);
            }

            public Builder toBuilder() {
                return newBuilder(this);
            }

            @java.lang.Override
            protected Builder newBuilderForType(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                Builder builder = new Builder(parent);
                return builder;
            }

            public static final class Builder extends
                    com.google.protobuf.GeneratedMessage.Builder<Builder>
                    implements com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiersOrBuilder {

                public static final com.google.protobuf.Descriptors.Descriptor
                        getDescriptor() {
                    return com.bw.application.message.ProduceSoldierMessage.internal_static_message_ProduceSoldiersRequest_ProduceSoldiers_descriptor;
                }

                protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
                        internalGetFieldAccessorTable() {
                    return com.bw.application.message.ProduceSoldierMessage.internal_static_message_ProduceSoldiersRequest_ProduceSoldiers_fieldAccessorTable;
                }

                // Construct using com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers.newBuilder()
                private Builder() {
                    maybeForceBuilderInitialization();
                }

                private Builder(BuilderParent parent) {
                    super(parent);
                    maybeForceBuilderInitialization();
                }

                private void maybeForceBuilderInitialization() {
                    if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                    }
                }

                private static Builder create() {
                    return new Builder();
                }

                public Builder clear() {
                    super.clear();
                    characterId_ = 0;
                    bitField0_ = (bitField0_ & ~0x00000001);
                    characterLevel_ = 0;
                    bitField0_ = (bitField0_ & ~0x00000002);
                    produceCount_ = 0;
                    bitField0_ = (bitField0_ & ~0x00000004);
                    index_ = 0;
                    bitField0_ = (bitField0_ & ~0x00000008);
                    uuid_ = 0;
                    bitField0_ = (bitField0_ & ~0x00000010);
                    return this;
                }

                public Builder clone() {
                    return create().mergeFrom(buildPartial());
                }

                public com.google.protobuf.Descriptors.Descriptor
                        getDescriptorForType() {
                    return com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers.getDescriptor();
                }

                public com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers getDefaultInstanceForType() {
                    return com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers.getDefaultInstance();
                }

                public com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers build() {
                    com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers result = buildPartial();
                    if (!result.isInitialized()) {
                        throw newUninitializedMessageException(result);
                    }
                    return result;
                }

                private com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers buildParsed()
                        throws com.google.protobuf.InvalidProtocolBufferException {
                    com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers result = buildPartial();
                    if (!result.isInitialized()) {
                        throw newUninitializedMessageException(
                                result).asInvalidProtocolBufferException();
                    }
                    return result;
                }

                public com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers buildPartial() {
                    com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers result = new com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers(this);
                    int from_bitField0_ = bitField0_;
                    int to_bitField0_ = 0;
                    if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                        to_bitField0_ |= 0x00000001;
                    }
                    result.characterId_ = characterId_;
                    if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                        to_bitField0_ |= 0x00000002;
                    }
                    result.characterLevel_ = characterLevel_;
                    if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                        to_bitField0_ |= 0x00000004;
                    }
                    result.produceCount_ = produceCount_;
                    if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
                        to_bitField0_ |= 0x00000008;
                    }
                    result.index_ = index_;
                    if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
                        to_bitField0_ |= 0x00000010;
                    }
                    result.uuid_ = uuid_;
                    result.bitField0_ = to_bitField0_;
                    onBuilt();
                    return result;
                }

                public Builder mergeFrom(com.google.protobuf.Message other) {
                    if (other instanceof com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers) {
                        return mergeFrom((com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers) other);
                    } else {
                        super.mergeFrom(other);
                        return this;
                    }
                }

                public Builder mergeFrom(com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers other) {
                    if (other == com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers.getDefaultInstance()) {
                        return this;
                    }
                    if (other.hasCharacterId()) {
                        setCharacterId(other.getCharacterId());
                    }
                    if (other.hasCharacterLevel()) {
                        setCharacterLevel(other.getCharacterLevel());
                    }
                    if (other.hasProduceCount()) {
                        setProduceCount(other.getProduceCount());
                    }
                    if (other.hasIndex()) {
                        setIndex(other.getIndex());
                    }
                    if (other.hasUuid()) {
                        setUuid(other.getUuid());
                    }
                    this.mergeUnknownFields(other.getUnknownFields());
                    return this;
                }

                public final boolean isInitialized() {
                    return true;
                }

                public Builder mergeFrom(
                        com.google.protobuf.CodedInputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws java.io.IOException {
                    com.google.protobuf.UnknownFieldSet.Builder unknownFields
                            = com.google.protobuf.UnknownFieldSet.newBuilder(
                                    this.getUnknownFields());
                    while (true) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                this.setUnknownFields(unknownFields.build());
                                onChanged();
                                return this;
                            default: {
                                if (!parseUnknownField(input, unknownFields,
                                        extensionRegistry, tag)) {
                                    this.setUnknownFields(unknownFields.build());
                                    onChanged();
                                    return this;
                                }
                                break;
                            }
                            case 8: {
                                bitField0_ |= 0x00000001;
                                characterId_ = input.readInt32();
                                break;
                            }
                            case 16: {
                                bitField0_ |= 0x00000002;
                                characterLevel_ = input.readInt32();
                                break;
                            }
                            case 24: {
                                bitField0_ |= 0x00000004;
                                produceCount_ = input.readInt32();
                                break;
                            }
                            case 32: {
                                bitField0_ |= 0x00000008;
                                index_ = input.readInt32();
                                break;
                            }
                            case 40: {
                                bitField0_ |= 0x00000010;
                                uuid_ = input.readInt32();
                                break;
                            }
                        }
                    }
                }

                private int bitField0_;

                // optional int32 character_id = 1;
                private int characterId_;

                public boolean hasCharacterId() {
                    return ((bitField0_ & 0x00000001) == 0x00000001);
                }

                public int getCharacterId() {
                    return characterId_;
                }

                public Builder setCharacterId(int value) {
                    bitField0_ |= 0x00000001;
                    characterId_ = value;
                    onChanged();
                    return this;
                }

                public Builder clearCharacterId() {
                    bitField0_ = (bitField0_ & ~0x00000001);
                    characterId_ = 0;
                    onChanged();
                    return this;
                }

                // optional int32 character_level = 2;
                private int characterLevel_;

                public boolean hasCharacterLevel() {
                    return ((bitField0_ & 0x00000002) == 0x00000002);
                }

                public int getCharacterLevel() {
                    return characterLevel_;
                }

                public Builder setCharacterLevel(int value) {
                    bitField0_ |= 0x00000002;
                    characterLevel_ = value;
                    onChanged();
                    return this;
                }

                public Builder clearCharacterLevel() {
                    bitField0_ = (bitField0_ & ~0x00000002);
                    characterLevel_ = 0;
                    onChanged();
                    return this;
                }

                // optional int32 produce_count = 3;
                private int produceCount_;

                public boolean hasProduceCount() {
                    return ((bitField0_ & 0x00000004) == 0x00000004);
                }

                public int getProduceCount() {
                    return produceCount_;
                }

                public Builder setProduceCount(int value) {
                    bitField0_ |= 0x00000004;
                    produceCount_ = value;
                    onChanged();
                    return this;
                }

                public Builder clearProduceCount() {
                    bitField0_ = (bitField0_ & ~0x00000004);
                    produceCount_ = 0;
                    onChanged();
                    return this;
                }

                // optional int32 index = 4;
                private int index_;

                public boolean hasIndex() {
                    return ((bitField0_ & 0x00000008) == 0x00000008);
                }

                public int getIndex() {
                    return index_;
                }

                public Builder setIndex(int value) {
                    bitField0_ |= 0x00000008;
                    index_ = value;
                    onChanged();
                    return this;
                }

                public Builder clearIndex() {
                    bitField0_ = (bitField0_ & ~0x00000008);
                    index_ = 0;
                    onChanged();
                    return this;
                }

                // optional int32 uuid = 5;
                private int uuid_;

                public boolean hasUuid() {
                    return ((bitField0_ & 0x00000010) == 0x00000010);
                }

                public int getUuid() {
                    return uuid_;
                }

                public Builder setUuid(int value) {
                    bitField0_ |= 0x00000010;
                    uuid_ = value;
                    onChanged();
                    return this;
                }

                public Builder clearUuid() {
                    bitField0_ = (bitField0_ & ~0x00000010);
                    uuid_ = 0;
                    onChanged();
                    return this;
                }

                // @@protoc_insertion_point(builder_scope:message.ProduceSoldiersRequest.ProduceSoldiers)
            }

            static {
                defaultInstance = new ProduceSoldiers(true);
                defaultInstance.initFields();
            }

            // @@protoc_insertion_point(class_scope:message.ProduceSoldiersRequest.ProduceSoldiers)
        }

        private int bitField0_;
        // required string mailAddress = 1;
        public static final int MAILADDRESS_FIELD_NUMBER = 1;
        private java.lang.Object mailAddress_;

        public boolean hasMailAddress() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        public String getMailAddress() {
            java.lang.Object ref = mailAddress_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs
                        = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    mailAddress_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getMailAddressBytes() {
            java.lang.Object ref = mailAddress_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b
                        = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                mailAddress_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // repeated .message.ProduceSoldiersRequest.ProduceSoldiers soldiersList = 2;
        public static final int SOLDIERSLIST_FIELD_NUMBER = 2;
        private java.util.List<com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers> soldiersList_;

        public java.util.List<com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers> getSoldiersListList() {
            return soldiersList_;
        }

        public java.util.List<? extends com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiersOrBuilder>
                getSoldiersListOrBuilderList() {
            return soldiersList_;
        }

        public int getSoldiersListCount() {
            return soldiersList_.size();
        }

        public com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers getSoldiersList(int index) {
            return soldiersList_.get(index);
        }

        public com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiersOrBuilder getSoldiersListOrBuilder(
                int index) {
            return soldiersList_.get(index);
        }

        // optional int32 create_state = 3;
        public static final int CREATE_STATE_FIELD_NUMBER = 3;
        private int createState_;

        public boolean hasCreateState() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        public int getCreateState() {
            return createState_;
        }

        private void initFields() {
            mailAddress_ = "";
            soldiersList_ = java.util.Collections.emptyList();
            createState_ = 0;
        }
        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) {
                return isInitialized == 1;
            }

            if (!hasMailAddress()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(1, getMailAddressBytes());
            }
            for (int i = 0; i < soldiersList_.size(); i++) {
                output.writeMessage(2, soldiersList_.get(i));
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeInt32(3, createState_);
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) {
                return size;
            }

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(1, getMailAddressBytes());
            }
            for (int i = 0; i < soldiersList_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(2, soldiersList_.get(i));
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(3, createState_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequestOrBuilder {

            public static final com.google.protobuf.Descriptors.Descriptor
                    getDescriptor() {
                return com.bw.application.message.ProduceSoldierMessage.internal_static_message_ProduceSoldiersRequest_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
                    internalGetFieldAccessorTable() {
                return com.bw.application.message.ProduceSoldierMessage.internal_static_message_ProduceSoldiersRequest_fieldAccessorTable;
            }

            // Construct using com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                    getSoldiersListFieldBuilder();
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                mailAddress_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                if (soldiersListBuilder_ == null) {
                    soldiersList_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000002);
                } else {
                    soldiersListBuilder_.clear();
                }
                createState_ = 0;
                bitField0_ = (bitField0_ & ~0x00000004);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
                    getDescriptorForType() {
                return com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.getDescriptor();
            }

            public com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest getDefaultInstanceForType() {
                return com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.getDefaultInstance();
            }

            public com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest build() {
                com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            private com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest buildParsed()
                    throws com.google.protobuf.InvalidProtocolBufferException {
                com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(
                            result).asInvalidProtocolBufferException();
                }
                return result;
            }

            public com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest buildPartial() {
                com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest result = new com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.mailAddress_ = mailAddress_;
                if (soldiersListBuilder_ == null) {
                    if (((bitField0_ & 0x00000002) == 0x00000002)) {
                        soldiersList_ = java.util.Collections.unmodifiableList(soldiersList_);
                        bitField0_ = (bitField0_ & ~0x00000002);
                    }
                    result.soldiersList_ = soldiersList_;
                } else {
                    result.soldiersList_ = soldiersListBuilder_.build();
                }
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.createState_ = createState_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest) {
                    return mergeFrom((com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest other) {
                if (other == com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.getDefaultInstance()) {
                    return this;
                }
                if (other.hasMailAddress()) {
                    setMailAddress(other.getMailAddress());
                }
                if (soldiersListBuilder_ == null) {
                    if (!other.soldiersList_.isEmpty()) {
                        if (soldiersList_.isEmpty()) {
                            soldiersList_ = other.soldiersList_;
                            bitField0_ = (bitField0_ & ~0x00000002);
                        } else {
                            ensureSoldiersListIsMutable();
                            soldiersList_.addAll(other.soldiersList_);
                        }
                        onChanged();
                    }
                } else if (!other.soldiersList_.isEmpty()) {
                    if (soldiersListBuilder_.isEmpty()) {
                        soldiersListBuilder_.dispose();
                        soldiersListBuilder_ = null;
                        soldiersList_ = other.soldiersList_;
                        bitField0_ = (bitField0_ & ~0x00000002);
                        soldiersListBuilder_
                                = com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders
                                        ? getSoldiersListFieldBuilder() : null;
                    } else {
                        soldiersListBuilder_.addAllMessages(other.soldiersList_);
                    }
                }
                if (other.hasCreateState()) {
                    setCreateState(other.getCreateState());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasMailAddress()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.google.protobuf.UnknownFieldSet.Builder unknownFields
                        = com.google.protobuf.UnknownFieldSet.newBuilder(
                                this.getUnknownFields());
                while (true) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            this.setUnknownFields(unknownFields.build());
                            onChanged();
                            return this;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                this.setUnknownFields(unknownFields.build());
                                onChanged();
                                return this;
                            }
                            break;
                        }
                        case 10: {
                            bitField0_ |= 0x00000001;
                            mailAddress_ = input.readBytes();
                            break;
                        }
                        case 18: {
                            com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers.Builder subBuilder = com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers.newBuilder();
                            input.readMessage(subBuilder, extensionRegistry);
                            addSoldiersList(subBuilder.buildPartial());
                            break;
                        }
                        case 24: {
                            bitField0_ |= 0x00000004;
                            createState_ = input.readInt32();
                            break;
                        }
                    }
                }
            }

            private int bitField0_;

            // required string mailAddress = 1;
            private java.lang.Object mailAddress_ = "";

            public boolean hasMailAddress() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            public String getMailAddress() {
                java.lang.Object ref = mailAddress_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    mailAddress_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            public Builder setMailAddress(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                mailAddress_ = value;
                onChanged();
                return this;
            }

            public Builder clearMailAddress() {
                bitField0_ = (bitField0_ & ~0x00000001);
                mailAddress_ = getDefaultInstance().getMailAddress();
                onChanged();
                return this;
            }

            void setMailAddress(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000001;
                mailAddress_ = value;
                onChanged();
            }

            // repeated .message.ProduceSoldiersRequest.ProduceSoldiers soldiersList = 2;
            private java.util.List<com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers> soldiersList_
                    = java.util.Collections.emptyList();

            private void ensureSoldiersListIsMutable() {
                if (!((bitField0_ & 0x00000002) == 0x00000002)) {
                    soldiersList_ = new java.util.ArrayList<com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers>(soldiersList_);
                    bitField0_ |= 0x00000002;
                }
            }

            private com.google.protobuf.RepeatedFieldBuilder<
          com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers, com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers.Builder, com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiersOrBuilder> soldiersListBuilder_;

            public java.util.List<com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers> getSoldiersListList() {
                if (soldiersListBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(soldiersList_);
                } else {
                    return soldiersListBuilder_.getMessageList();
                }
            }

            public int getSoldiersListCount() {
                if (soldiersListBuilder_ == null) {
                    return soldiersList_.size();
                } else {
                    return soldiersListBuilder_.getCount();
                }
            }

            public com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers getSoldiersList(int index) {
                if (soldiersListBuilder_ == null) {
                    return soldiersList_.get(index);
                } else {
                    return soldiersListBuilder_.getMessage(index);
                }
            }

            public Builder setSoldiersList(
                    int index, com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers value) {
                if (soldiersListBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureSoldiersListIsMutable();
                    soldiersList_.set(index, value);
                    onChanged();
                } else {
                    soldiersListBuilder_.setMessage(index, value);
                }
                return this;
            }

            public Builder setSoldiersList(
                    int index, com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers.Builder builderForValue) {
                if (soldiersListBuilder_ == null) {
                    ensureSoldiersListIsMutable();
                    soldiersList_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    soldiersListBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }

            public Builder addSoldiersList(com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers value) {
                if (soldiersListBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureSoldiersListIsMutable();
                    soldiersList_.add(value);
                    onChanged();
                } else {
                    soldiersListBuilder_.addMessage(value);
                }
                return this;
            }

            public Builder addSoldiersList(
                    int index, com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers value) {
                if (soldiersListBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureSoldiersListIsMutable();
                    soldiersList_.add(index, value);
                    onChanged();
                } else {
                    soldiersListBuilder_.addMessage(index, value);
                }
                return this;
            }

            public Builder addSoldiersList(
                    com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers.Builder builderForValue) {
                if (soldiersListBuilder_ == null) {
                    ensureSoldiersListIsMutable();
                    soldiersList_.add(builderForValue.build());
                    onChanged();
                } else {
                    soldiersListBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }

            public Builder addSoldiersList(
                    int index, com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers.Builder builderForValue) {
                if (soldiersListBuilder_ == null) {
                    ensureSoldiersListIsMutable();
                    soldiersList_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    soldiersListBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }

            public Builder addAllSoldiersList(
                    java.lang.Iterable<? extends com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers> values) {
                if (soldiersListBuilder_ == null) {
                    ensureSoldiersListIsMutable();
                    super.addAll(values, soldiersList_);
                    onChanged();
                } else {
                    soldiersListBuilder_.addAllMessages(values);
                }
                return this;
            }

            public Builder clearSoldiersList() {
                if (soldiersListBuilder_ == null) {
                    soldiersList_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000002);
                    onChanged();
                } else {
                    soldiersListBuilder_.clear();
                }
                return this;
            }

            public Builder removeSoldiersList(int index) {
                if (soldiersListBuilder_ == null) {
                    ensureSoldiersListIsMutable();
                    soldiersList_.remove(index);
                    onChanged();
                } else {
                    soldiersListBuilder_.remove(index);
                }
                return this;
            }

            public com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers.Builder getSoldiersListBuilder(
                    int index) {
                return getSoldiersListFieldBuilder().getBuilder(index);
            }

            public com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiersOrBuilder getSoldiersListOrBuilder(
                    int index) {
                if (soldiersListBuilder_ == null) {
                    return soldiersList_.get(index);
                } else {
                    return soldiersListBuilder_.getMessageOrBuilder(index);
                }
            }

            public java.util.List<? extends com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiersOrBuilder>
                    getSoldiersListOrBuilderList() {
                if (soldiersListBuilder_ != null) {
                    return soldiersListBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(soldiersList_);
                }
            }

            public com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers.Builder addSoldiersListBuilder() {
                return getSoldiersListFieldBuilder().addBuilder(
                        com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers.getDefaultInstance());
            }

            public com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers.Builder addSoldiersListBuilder(
                    int index) {
                return getSoldiersListFieldBuilder().addBuilder(
                        index, com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers.getDefaultInstance());
            }

            public java.util.List<com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers.Builder>
                    getSoldiersListBuilderList() {
                return getSoldiersListFieldBuilder().getBuilderList();
            }

            private com.google.protobuf.RepeatedFieldBuilder<
          com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers, com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers.Builder, com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiersOrBuilder>
                    getSoldiersListFieldBuilder() {
                if (soldiersListBuilder_ == null) {
                    soldiersListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers, com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers.Builder, com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiersOrBuilder>(
                            soldiersList_,
                            ((bitField0_ & 0x00000002) == 0x00000002),
                            getParentForChildren(),
                            isClean());
                    soldiersList_ = null;
                }
                return soldiersListBuilder_;
            }

            // optional int32 create_state = 3;
            private int createState_;

            public boolean hasCreateState() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            public int getCreateState() {
                return createState_;
            }

            public Builder setCreateState(int value) {
                bitField0_ |= 0x00000004;
                createState_ = value;
                onChanged();
                return this;
            }

            public Builder clearCreateState() {
                bitField0_ = (bitField0_ & ~0x00000004);
                createState_ = 0;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:message.ProduceSoldiersRequest)
        }

        static {
            defaultInstance = new ProduceSoldiersRequest(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:message.ProduceSoldiersRequest)
    }

    public interface ProduceSoldiersResponseOrBuilder
            extends com.google.protobuf.MessageOrBuilder {

        // optional sint32 result = 1;
        boolean hasResult();

        int getResult();

        // optional string info = 2;
        boolean hasInfo();

        String getInfo();
    }

    public static final class ProduceSoldiersResponse extends
            com.google.protobuf.GeneratedMessage
            implements ProduceSoldiersResponseOrBuilder {
        // Use ProduceSoldiersResponse.newBuilder() to construct.

        private ProduceSoldiersResponse(Builder builder) {
            super(builder);
        }

        private ProduceSoldiersResponse(boolean noInit) {
        }

        private static final ProduceSoldiersResponse defaultInstance;

        public static ProduceSoldiersResponse getDefaultInstance() {
            return defaultInstance;
        }

        public ProduceSoldiersResponse getDefaultInstanceForType() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
                getDescriptor() {
            return com.bw.application.message.ProduceSoldierMessage.internal_static_message_ProduceSoldiersResponse_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
                internalGetFieldAccessorTable() {
            return com.bw.application.message.ProduceSoldierMessage.internal_static_message_ProduceSoldiersResponse_fieldAccessorTable;
        }

        private int bitField0_;
        // optional sint32 result = 1;
        public static final int RESULT_FIELD_NUMBER = 1;
        private int result_;

        public boolean hasResult() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        public int getResult() {
            return result_;
        }

        // optional string info = 2;
        public static final int INFO_FIELD_NUMBER = 2;
        private java.lang.Object info_;

        public boolean hasInfo() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        public String getInfo() {
            java.lang.Object ref = info_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs
                        = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    info_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getInfoBytes() {
            java.lang.Object ref = info_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b
                        = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                info_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private void initFields() {
            result_ = 0;
            info_ = "";
        }
        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) {
                return isInitialized == 1;
            }

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeSInt32(1, result_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(2, getInfoBytes());
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) {
                return size;
            }

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeSInt32Size(1, result_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, getInfoBytes());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersResponse parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersResponse parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersResponse parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersResponse parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersResponse parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersResponse parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersResponse parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersResponse parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersResponse parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersResponse parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersResponse prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersResponseOrBuilder {

            public static final com.google.protobuf.Descriptors.Descriptor
                    getDescriptor() {
                return com.bw.application.message.ProduceSoldierMessage.internal_static_message_ProduceSoldiersResponse_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
                    internalGetFieldAccessorTable() {
                return com.bw.application.message.ProduceSoldierMessage.internal_static_message_ProduceSoldiersResponse_fieldAccessorTable;
            }

            // Construct using com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersResponse.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                result_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                info_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
                    getDescriptorForType() {
                return com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersResponse.getDescriptor();
            }

            public com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersResponse getDefaultInstanceForType() {
                return com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersResponse.getDefaultInstance();
            }

            public com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersResponse build() {
                com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            private com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersResponse buildParsed()
                    throws com.google.protobuf.InvalidProtocolBufferException {
                com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(
                            result).asInvalidProtocolBufferException();
                }
                return result;
            }

            public com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersResponse buildPartial() {
                com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersResponse result = new com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersResponse(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.result_ = result_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.info_ = info_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersResponse) {
                    return mergeFrom((com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersResponse) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersResponse other) {
                if (other == com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersResponse.getDefaultInstance()) {
                    return this;
                }
                if (other.hasResult()) {
                    setResult(other.getResult());
                }
                if (other.hasInfo()) {
                    setInfo(other.getInfo());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.google.protobuf.UnknownFieldSet.Builder unknownFields
                        = com.google.protobuf.UnknownFieldSet.newBuilder(
                                this.getUnknownFields());
                while (true) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            this.setUnknownFields(unknownFields.build());
                            onChanged();
                            return this;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                this.setUnknownFields(unknownFields.build());
                                onChanged();
                                return this;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            result_ = input.readSInt32();
                            break;
                        }
                        case 18: {
                            bitField0_ |= 0x00000002;
                            info_ = input.readBytes();
                            break;
                        }
                    }
                }
            }

            private int bitField0_;

            // optional sint32 result = 1;
            private int result_;

            public boolean hasResult() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            public int getResult() {
                return result_;
            }

            public Builder setResult(int value) {
                bitField0_ |= 0x00000001;
                result_ = value;
                onChanged();
                return this;
            }

            public Builder clearResult() {
                bitField0_ = (bitField0_ & ~0x00000001);
                result_ = 0;
                onChanged();
                return this;
            }

            // optional string info = 2;
            private java.lang.Object info_ = "";

            public boolean hasInfo() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            public String getInfo() {
                java.lang.Object ref = info_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    info_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            public Builder setInfo(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                info_ = value;
                onChanged();
                return this;
            }

            public Builder clearInfo() {
                bitField0_ = (bitField0_ & ~0x00000002);
                info_ = getDefaultInstance().getInfo();
                onChanged();
                return this;
            }

            void setInfo(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000002;
                info_ = value;
                onChanged();
            }

            // @@protoc_insertion_point(builder_scope:message.ProduceSoldiersResponse)
        }

        static {
            defaultInstance = new ProduceSoldiersResponse(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:message.ProduceSoldiersResponse)
    }

    private static com.google.protobuf.Descriptors.Descriptor internal_static_message_ProduceSoldiersRequest_descriptor;
    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_message_ProduceSoldiersRequest_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.Descriptor internal_static_message_ProduceSoldiersRequest_ProduceSoldiers_descriptor;
    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_message_ProduceSoldiersRequest_ProduceSoldiers_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.Descriptor internal_static_message_ProduceSoldiersResponse_descriptor;
    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_message_ProduceSoldiersResponse_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
            getDescriptor() {
        return descriptor;
    }
    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

    static {
        java.lang.String[] descriptorData = {
            "\n\033ProduceSoldierMessage.proto\022\007message\"\200"
            + "\002\n\026ProduceSoldiersRequest\022\023\n\013mailAddress"
            + "\030\001 \002(\t\022E\n\014soldiersList\030\002 \003(\0132/.message.P"
            + "roduceSoldiersRequest.ProduceSoldiers\022\024\n"
            + "\014create_state\030\003 \001(\005\032t\n\017ProduceSoldiers\022\024"
            + "\n\014character_id\030\001 \001(\005\022\027\n\017character_level\030"
            + "\002 \001(\005\022\025\n\rproduce_count\030\003 \001(\005\022\r\n\005index\030\004 "
            + "\001(\005\022\014\n\004uuid\030\005 \001(\005\"7\n\027ProduceSoldiersResp"
            + "onse\022\016\n\006result\030\001 \001(\021\022\014\n\004info\030\002 \001(\tB3\n\032co"
            + "m.bw.application.messageB\025ProduceSoldier",
            "Message"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner
                = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
            public com.google.protobuf.ExtensionRegistry assignDescriptors(
                    com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                internal_static_message_ProduceSoldiersRequest_descriptor
                        = getDescriptor().getMessageTypes().get(0);
                internal_static_message_ProduceSoldiersRequest_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                        internal_static_message_ProduceSoldiersRequest_descriptor,
                        new java.lang.String[]{"MailAddress", "SoldiersList", "CreateState",},
                        com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.class,
                        com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.Builder.class);
                internal_static_message_ProduceSoldiersRequest_ProduceSoldiers_descriptor
                        = internal_static_message_ProduceSoldiersRequest_descriptor.getNestedTypes().get(0);
                internal_static_message_ProduceSoldiersRequest_ProduceSoldiers_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                        internal_static_message_ProduceSoldiersRequest_ProduceSoldiers_descriptor,
                        new java.lang.String[]{"CharacterId", "CharacterLevel", "ProduceCount", "Index", "Uuid",},
                        com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers.class,
                        com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersRequest.ProduceSoldiers.Builder.class);
                internal_static_message_ProduceSoldiersResponse_descriptor
                        = getDescriptor().getMessageTypes().get(1);
                internal_static_message_ProduceSoldiersResponse_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                        internal_static_message_ProduceSoldiersResponse_descriptor,
                        new java.lang.String[]{"Result", "Info",},
                        com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersResponse.class,
                        com.bw.application.message.ProduceSoldierMessage.ProduceSoldiersResponse.Builder.class);
                return null;
            }
        };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{}, assigner);
    }

    // @@protoc_insertion_point(outer_class_scope)
}
