// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RevengeBattle.proto
package com.bw.application.message;

public final class RevengeBattle {

    private RevengeBattle() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }

    public interface RevengeBattleRequestOrBuilder
            extends com.google.protobuf.MessageOrBuilder {

        // required string mailAddress = 1;
        boolean hasMailAddress();

        String getMailAddress();

        // optional string defenceMailAddress = 2;
        boolean hasDefenceMailAddress();

        String getDefenceMailAddress();
    }

    public static final class RevengeBattleRequest extends
            com.google.protobuf.GeneratedMessage
            implements RevengeBattleRequestOrBuilder {
        // Use RevengeBattleRequest.newBuilder() to construct.

        private RevengeBattleRequest(Builder builder) {
            super(builder);
        }

        private RevengeBattleRequest(boolean noInit) {
        }

        private static final RevengeBattleRequest defaultInstance;

        public static RevengeBattleRequest getDefaultInstance() {
            return defaultInstance;
        }

        public RevengeBattleRequest getDefaultInstanceForType() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
                getDescriptor() {
            return com.bw.application.message.RevengeBattle.internal_static_message_RevengeBattleRequest_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
                internalGetFieldAccessorTable() {
            return com.bw.application.message.RevengeBattle.internal_static_message_RevengeBattleRequest_fieldAccessorTable;
        }

        private int bitField0_;
        // required string mailAddress = 1;
        public static final int MAILADDRESS_FIELD_NUMBER = 1;
        private java.lang.Object mailAddress_;

        public boolean hasMailAddress() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        public String getMailAddress() {
            java.lang.Object ref = mailAddress_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs
                        = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    mailAddress_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getMailAddressBytes() {
            java.lang.Object ref = mailAddress_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b
                        = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                mailAddress_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // optional string defenceMailAddress = 2;
        public static final int DEFENCEMAILADDRESS_FIELD_NUMBER = 2;
        private java.lang.Object defenceMailAddress_;

        public boolean hasDefenceMailAddress() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        public String getDefenceMailAddress() {
            java.lang.Object ref = defenceMailAddress_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs
                        = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    defenceMailAddress_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getDefenceMailAddressBytes() {
            java.lang.Object ref = defenceMailAddress_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b
                        = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                defenceMailAddress_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private void initFields() {
            mailAddress_ = "";
            defenceMailAddress_ = "";
        }
        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) {
                return isInitialized == 1;
            }

            if (!hasMailAddress()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(1, getMailAddressBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(2, getDefenceMailAddressBytes());
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) {
                return size;
            }

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(1, getMailAddressBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, getDefenceMailAddressBytes());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static com.bw.application.message.RevengeBattle.RevengeBattleRequest parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static com.bw.application.message.RevengeBattle.RevengeBattleRequest parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static com.bw.application.message.RevengeBattle.RevengeBattleRequest parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static com.bw.application.message.RevengeBattle.RevengeBattleRequest parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static com.bw.application.message.RevengeBattle.RevengeBattleRequest parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static com.bw.application.message.RevengeBattle.RevengeBattleRequest parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static com.bw.application.message.RevengeBattle.RevengeBattleRequest parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static com.bw.application.message.RevengeBattle.RevengeBattleRequest parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static com.bw.application.message.RevengeBattle.RevengeBattleRequest parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static com.bw.application.message.RevengeBattle.RevengeBattleRequest parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(com.bw.application.message.RevengeBattle.RevengeBattleRequest prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements com.bw.application.message.RevengeBattle.RevengeBattleRequestOrBuilder {

            public static final com.google.protobuf.Descriptors.Descriptor
                    getDescriptor() {
                return com.bw.application.message.RevengeBattle.internal_static_message_RevengeBattleRequest_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
                    internalGetFieldAccessorTable() {
                return com.bw.application.message.RevengeBattle.internal_static_message_RevengeBattleRequest_fieldAccessorTable;
            }

            // Construct using com.bw.application.message.RevengeBattle.RevengeBattleRequest.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                mailAddress_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                defenceMailAddress_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
                    getDescriptorForType() {
                return com.bw.application.message.RevengeBattle.RevengeBattleRequest.getDescriptor();
            }

            public com.bw.application.message.RevengeBattle.RevengeBattleRequest getDefaultInstanceForType() {
                return com.bw.application.message.RevengeBattle.RevengeBattleRequest.getDefaultInstance();
            }

            public com.bw.application.message.RevengeBattle.RevengeBattleRequest build() {
                com.bw.application.message.RevengeBattle.RevengeBattleRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            private com.bw.application.message.RevengeBattle.RevengeBattleRequest buildParsed()
                    throws com.google.protobuf.InvalidProtocolBufferException {
                com.bw.application.message.RevengeBattle.RevengeBattleRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(
                            result).asInvalidProtocolBufferException();
                }
                return result;
            }

            public com.bw.application.message.RevengeBattle.RevengeBattleRequest buildPartial() {
                com.bw.application.message.RevengeBattle.RevengeBattleRequest result = new com.bw.application.message.RevengeBattle.RevengeBattleRequest(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.mailAddress_ = mailAddress_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.defenceMailAddress_ = defenceMailAddress_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.bw.application.message.RevengeBattle.RevengeBattleRequest) {
                    return mergeFrom((com.bw.application.message.RevengeBattle.RevengeBattleRequest) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.bw.application.message.RevengeBattle.RevengeBattleRequest other) {
                if (other == com.bw.application.message.RevengeBattle.RevengeBattleRequest.getDefaultInstance()) {
                    return this;
                }
                if (other.hasMailAddress()) {
                    setMailAddress(other.getMailAddress());
                }
                if (other.hasDefenceMailAddress()) {
                    setDefenceMailAddress(other.getDefenceMailAddress());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasMailAddress()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.google.protobuf.UnknownFieldSet.Builder unknownFields
                        = com.google.protobuf.UnknownFieldSet.newBuilder(
                                this.getUnknownFields());
                while (true) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            this.setUnknownFields(unknownFields.build());
                            onChanged();
                            return this;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                this.setUnknownFields(unknownFields.build());
                                onChanged();
                                return this;
                            }
                            break;
                        }
                        case 10: {
                            bitField0_ |= 0x00000001;
                            mailAddress_ = input.readBytes();
                            break;
                        }
                        case 18: {
                            bitField0_ |= 0x00000002;
                            defenceMailAddress_ = input.readBytes();
                            break;
                        }
                    }
                }
            }

            private int bitField0_;

            // required string mailAddress = 1;
            private java.lang.Object mailAddress_ = "";

            public boolean hasMailAddress() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            public String getMailAddress() {
                java.lang.Object ref = mailAddress_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    mailAddress_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            public Builder setMailAddress(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                mailAddress_ = value;
                onChanged();
                return this;
            }

            public Builder clearMailAddress() {
                bitField0_ = (bitField0_ & ~0x00000001);
                mailAddress_ = getDefaultInstance().getMailAddress();
                onChanged();
                return this;
            }

            void setMailAddress(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000001;
                mailAddress_ = value;
                onChanged();
            }

            // optional string defenceMailAddress = 2;
            private java.lang.Object defenceMailAddress_ = "";

            public boolean hasDefenceMailAddress() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            public String getDefenceMailAddress() {
                java.lang.Object ref = defenceMailAddress_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    defenceMailAddress_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            public Builder setDefenceMailAddress(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                defenceMailAddress_ = value;
                onChanged();
                return this;
            }

            public Builder clearDefenceMailAddress() {
                bitField0_ = (bitField0_ & ~0x00000002);
                defenceMailAddress_ = getDefaultInstance().getDefenceMailAddress();
                onChanged();
                return this;
            }

            void setDefenceMailAddress(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000002;
                defenceMailAddress_ = value;
                onChanged();
            }

            // @@protoc_insertion_point(builder_scope:message.RevengeBattleRequest)
        }

        static {
            defaultInstance = new RevengeBattleRequest(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:message.RevengeBattleRequest)
    }

    public interface RevengeBattleResponseOrBuilder
            extends com.google.protobuf.MessageOrBuilder {

        // optional sint32 result = 1 [default = 0];
        boolean hasResult();

        int getResult();

        // optional string info = 2;
        boolean hasInfo();

        String getInfo();
    }

    public static final class RevengeBattleResponse extends
            com.google.protobuf.GeneratedMessage
            implements RevengeBattleResponseOrBuilder {
        // Use RevengeBattleResponse.newBuilder() to construct.

        private RevengeBattleResponse(Builder builder) {
            super(builder);
        }

        private RevengeBattleResponse(boolean noInit) {
        }

        private static final RevengeBattleResponse defaultInstance;

        public static RevengeBattleResponse getDefaultInstance() {
            return defaultInstance;
        }

        public RevengeBattleResponse getDefaultInstanceForType() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
                getDescriptor() {
            return com.bw.application.message.RevengeBattle.internal_static_message_RevengeBattleResponse_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
                internalGetFieldAccessorTable() {
            return com.bw.application.message.RevengeBattle.internal_static_message_RevengeBattleResponse_fieldAccessorTable;
        }

        private int bitField0_;
        // optional sint32 result = 1 [default = 0];
        public static final int RESULT_FIELD_NUMBER = 1;
        private int result_;

        public boolean hasResult() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        public int getResult() {
            return result_;
        }

        // optional string info = 2;
        public static final int INFO_FIELD_NUMBER = 2;
        private java.lang.Object info_;

        public boolean hasInfo() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        public String getInfo() {
            java.lang.Object ref = info_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs
                        = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    info_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getInfoBytes() {
            java.lang.Object ref = info_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b
                        = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                info_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private void initFields() {
            result_ = 0;
            info_ = "";
        }
        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) {
                return isInitialized == 1;
            }

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeSInt32(1, result_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(2, getInfoBytes());
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) {
                return size;
            }

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeSInt32Size(1, result_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, getInfoBytes());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static com.bw.application.message.RevengeBattle.RevengeBattleResponse parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static com.bw.application.message.RevengeBattle.RevengeBattleResponse parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static com.bw.application.message.RevengeBattle.RevengeBattleResponse parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static com.bw.application.message.RevengeBattle.RevengeBattleResponse parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static com.bw.application.message.RevengeBattle.RevengeBattleResponse parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static com.bw.application.message.RevengeBattle.RevengeBattleResponse parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static com.bw.application.message.RevengeBattle.RevengeBattleResponse parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static com.bw.application.message.RevengeBattle.RevengeBattleResponse parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static com.bw.application.message.RevengeBattle.RevengeBattleResponse parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static com.bw.application.message.RevengeBattle.RevengeBattleResponse parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(com.bw.application.message.RevengeBattle.RevengeBattleResponse prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements com.bw.application.message.RevengeBattle.RevengeBattleResponseOrBuilder {

            public static final com.google.protobuf.Descriptors.Descriptor
                    getDescriptor() {
                return com.bw.application.message.RevengeBattle.internal_static_message_RevengeBattleResponse_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
                    internalGetFieldAccessorTable() {
                return com.bw.application.message.RevengeBattle.internal_static_message_RevengeBattleResponse_fieldAccessorTable;
            }

            // Construct using com.bw.application.message.RevengeBattle.RevengeBattleResponse.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                result_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                info_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
                    getDescriptorForType() {
                return com.bw.application.message.RevengeBattle.RevengeBattleResponse.getDescriptor();
            }

            public com.bw.application.message.RevengeBattle.RevengeBattleResponse getDefaultInstanceForType() {
                return com.bw.application.message.RevengeBattle.RevengeBattleResponse.getDefaultInstance();
            }

            public com.bw.application.message.RevengeBattle.RevengeBattleResponse build() {
                com.bw.application.message.RevengeBattle.RevengeBattleResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            private com.bw.application.message.RevengeBattle.RevengeBattleResponse buildParsed()
                    throws com.google.protobuf.InvalidProtocolBufferException {
                com.bw.application.message.RevengeBattle.RevengeBattleResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(
                            result).asInvalidProtocolBufferException();
                }
                return result;
            }

            public com.bw.application.message.RevengeBattle.RevengeBattleResponse buildPartial() {
                com.bw.application.message.RevengeBattle.RevengeBattleResponse result = new com.bw.application.message.RevengeBattle.RevengeBattleResponse(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.result_ = result_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.info_ = info_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.bw.application.message.RevengeBattle.RevengeBattleResponse) {
                    return mergeFrom((com.bw.application.message.RevengeBattle.RevengeBattleResponse) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.bw.application.message.RevengeBattle.RevengeBattleResponse other) {
                if (other == com.bw.application.message.RevengeBattle.RevengeBattleResponse.getDefaultInstance()) {
                    return this;
                }
                if (other.hasResult()) {
                    setResult(other.getResult());
                }
                if (other.hasInfo()) {
                    setInfo(other.getInfo());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.google.protobuf.UnknownFieldSet.Builder unknownFields
                        = com.google.protobuf.UnknownFieldSet.newBuilder(
                                this.getUnknownFields());
                while (true) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            this.setUnknownFields(unknownFields.build());
                            onChanged();
                            return this;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                this.setUnknownFields(unknownFields.build());
                                onChanged();
                                return this;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            result_ = input.readSInt32();
                            break;
                        }
                        case 18: {
                            bitField0_ |= 0x00000002;
                            info_ = input.readBytes();
                            break;
                        }
                    }
                }
            }

            private int bitField0_;

            // optional sint32 result = 1 [default = 0];
            private int result_;

            public boolean hasResult() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            public int getResult() {
                return result_;
            }

            public Builder setResult(int value) {
                bitField0_ |= 0x00000001;
                result_ = value;
                onChanged();
                return this;
            }

            public Builder clearResult() {
                bitField0_ = (bitField0_ & ~0x00000001);
                result_ = 0;
                onChanged();
                return this;
            }

            // optional string info = 2;
            private java.lang.Object info_ = "";

            public boolean hasInfo() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            public String getInfo() {
                java.lang.Object ref = info_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    info_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            public Builder setInfo(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                info_ = value;
                onChanged();
                return this;
            }

            public Builder clearInfo() {
                bitField0_ = (bitField0_ & ~0x00000002);
                info_ = getDefaultInstance().getInfo();
                onChanged();
                return this;
            }

            void setInfo(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000002;
                info_ = value;
                onChanged();
            }

            // @@protoc_insertion_point(builder_scope:message.RevengeBattleResponse)
        }

        static {
            defaultInstance = new RevengeBattleResponse(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:message.RevengeBattleResponse)
    }

    private static com.google.protobuf.Descriptors.Descriptor internal_static_message_RevengeBattleRequest_descriptor;
    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_message_RevengeBattleRequest_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.Descriptor internal_static_message_RevengeBattleResponse_descriptor;
    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_message_RevengeBattleResponse_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
            getDescriptor() {
        return descriptor;
    }
    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

    static {
        java.lang.String[] descriptorData = {
            "\n\023RevengeBattle.proto\022\007message\"G\n\024Reveng"
            + "eBattleRequest\022\023\n\013mailAddress\030\001 \002(\t\022\032\n\022d"
            + "efenceMailAddress\030\002 \001(\t\"8\n\025RevengeBattle"
            + "Response\022\021\n\006result\030\001 \001(\021:\0010\022\014\n\004info\030\002 \001("
            + "\tB+\n\032com.bw.application.messageB\rRevenge"
            + "Battle"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner
                = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
            public com.google.protobuf.ExtensionRegistry assignDescriptors(
                    com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                internal_static_message_RevengeBattleRequest_descriptor
                        = getDescriptor().getMessageTypes().get(0);
                internal_static_message_RevengeBattleRequest_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                        internal_static_message_RevengeBattleRequest_descriptor,
                        new java.lang.String[]{"MailAddress", "DefenceMailAddress",},
                        com.bw.application.message.RevengeBattle.RevengeBattleRequest.class,
                        com.bw.application.message.RevengeBattle.RevengeBattleRequest.Builder.class);
                internal_static_message_RevengeBattleResponse_descriptor
                        = getDescriptor().getMessageTypes().get(1);
                internal_static_message_RevengeBattleResponse_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                        internal_static_message_RevengeBattleResponse_descriptor,
                        new java.lang.String[]{"Result", "Info",},
                        com.bw.application.message.RevengeBattle.RevengeBattleResponse.class,
                        com.bw.application.message.RevengeBattle.RevengeBattleResponse.Builder.class);
                return null;
            }
        };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{}, assigner);
    }

    // @@protoc_insertion_point(outer_class_scope)
}
