// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AreaList.proto
package com.bw.application.message;

public final class AreaList {

    private AreaList() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }

    public interface AreaListRequestOrBuilder
            extends com.google.protobuf.MessageOrBuilder {

        // required string mac_address = 1;
        boolean hasMacAddress();

        String getMacAddress();
    }

    public static final class AreaListRequest extends
            com.google.protobuf.GeneratedMessage
            implements AreaListRequestOrBuilder {
        // Use AreaListRequest.newBuilder() to construct.

        private AreaListRequest(Builder builder) {
            super(builder);
        }

        private AreaListRequest(boolean noInit) {
        }

        private static final AreaListRequest defaultInstance;

        public static AreaListRequest getDefaultInstance() {
            return defaultInstance;
        }

        public AreaListRequest getDefaultInstanceForType() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
                getDescriptor() {
            return com.bw.application.message.AreaList.internal_static_message_AreaListRequest_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
                internalGetFieldAccessorTable() {
            return com.bw.application.message.AreaList.internal_static_message_AreaListRequest_fieldAccessorTable;
        }

        private int bitField0_;
        // required string mac_address = 1;
        public static final int MAC_ADDRESS_FIELD_NUMBER = 1;
        private java.lang.Object macAddress_;

        public boolean hasMacAddress() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        public String getMacAddress() {
            java.lang.Object ref = macAddress_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs
                        = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    macAddress_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getMacAddressBytes() {
            java.lang.Object ref = macAddress_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b
                        = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                macAddress_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private void initFields() {
            macAddress_ = "";
        }
        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) {
                return isInitialized == 1;
            }

            if (!hasMacAddress()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(1, getMacAddressBytes());
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) {
                return size;
            }

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(1, getMacAddressBytes());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static com.bw.application.message.AreaList.AreaListRequest parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static com.bw.application.message.AreaList.AreaListRequest parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static com.bw.application.message.AreaList.AreaListRequest parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static com.bw.application.message.AreaList.AreaListRequest parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static com.bw.application.message.AreaList.AreaListRequest parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static com.bw.application.message.AreaList.AreaListRequest parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static com.bw.application.message.AreaList.AreaListRequest parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static com.bw.application.message.AreaList.AreaListRequest parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static com.bw.application.message.AreaList.AreaListRequest parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static com.bw.application.message.AreaList.AreaListRequest parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(com.bw.application.message.AreaList.AreaListRequest prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements com.bw.application.message.AreaList.AreaListRequestOrBuilder {

            public static final com.google.protobuf.Descriptors.Descriptor
                    getDescriptor() {
                return com.bw.application.message.AreaList.internal_static_message_AreaListRequest_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
                    internalGetFieldAccessorTable() {
                return com.bw.application.message.AreaList.internal_static_message_AreaListRequest_fieldAccessorTable;
            }

            // Construct using com.bw.application.message.AreaList.AreaListRequest.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                macAddress_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
                    getDescriptorForType() {
                return com.bw.application.message.AreaList.AreaListRequest.getDescriptor();
            }

            public com.bw.application.message.AreaList.AreaListRequest getDefaultInstanceForType() {
                return com.bw.application.message.AreaList.AreaListRequest.getDefaultInstance();
            }

            public com.bw.application.message.AreaList.AreaListRequest build() {
                com.bw.application.message.AreaList.AreaListRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            private com.bw.application.message.AreaList.AreaListRequest buildParsed()
                    throws com.google.protobuf.InvalidProtocolBufferException {
                com.bw.application.message.AreaList.AreaListRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(
                            result).asInvalidProtocolBufferException();
                }
                return result;
            }

            public com.bw.application.message.AreaList.AreaListRequest buildPartial() {
                com.bw.application.message.AreaList.AreaListRequest result = new com.bw.application.message.AreaList.AreaListRequest(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.macAddress_ = macAddress_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.bw.application.message.AreaList.AreaListRequest) {
                    return mergeFrom((com.bw.application.message.AreaList.AreaListRequest) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.bw.application.message.AreaList.AreaListRequest other) {
                if (other == com.bw.application.message.AreaList.AreaListRequest.getDefaultInstance()) {
                    return this;
                }
                if (other.hasMacAddress()) {
                    setMacAddress(other.getMacAddress());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasMacAddress()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.google.protobuf.UnknownFieldSet.Builder unknownFields
                        = com.google.protobuf.UnknownFieldSet.newBuilder(
                                this.getUnknownFields());
                while (true) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            this.setUnknownFields(unknownFields.build());
                            onChanged();
                            return this;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                this.setUnknownFields(unknownFields.build());
                                onChanged();
                                return this;
                            }
                            break;
                        }
                        case 10: {
                            bitField0_ |= 0x00000001;
                            macAddress_ = input.readBytes();
                            break;
                        }
                    }
                }
            }

            private int bitField0_;

            // required string mac_address = 1;
            private java.lang.Object macAddress_ = "";

            public boolean hasMacAddress() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            public String getMacAddress() {
                java.lang.Object ref = macAddress_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    macAddress_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            public Builder setMacAddress(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                macAddress_ = value;
                onChanged();
                return this;
            }

            public Builder clearMacAddress() {
                bitField0_ = (bitField0_ & ~0x00000001);
                macAddress_ = getDefaultInstance().getMacAddress();
                onChanged();
                return this;
            }

            void setMacAddress(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000001;
                macAddress_ = value;
                onChanged();
            }

            // @@protoc_insertion_point(builder_scope:message.AreaListRequest)
        }

        static {
            defaultInstance = new AreaListRequest(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:message.AreaListRequest)
    }

    public interface AreaListResponseOrBuilder
            extends com.google.protobuf.MessageOrBuilder {

        // optional sint32 result = 1;
        boolean hasResult();

        int getResult();

        // optional string info = 2;
        boolean hasInfo();

        String getInfo();

        // repeated .message.AreaListResponse.AreaData areaDataList = 3;
        java.util.List<com.bw.application.message.AreaList.AreaListResponse.AreaData>
                getAreaDataListList();

        com.bw.application.message.AreaList.AreaListResponse.AreaData getAreaDataList(int index);

        int getAreaDataListCount();

        java.util.List<? extends com.bw.application.message.AreaList.AreaListResponse.AreaDataOrBuilder>
                getAreaDataListOrBuilderList();

        com.bw.application.message.AreaList.AreaListResponse.AreaDataOrBuilder getAreaDataListOrBuilder(
                int index);
    }

    public static final class AreaListResponse extends
            com.google.protobuf.GeneratedMessage
            implements AreaListResponseOrBuilder {
        // Use AreaListResponse.newBuilder() to construct.

        private AreaListResponse(Builder builder) {
            super(builder);
        }

        private AreaListResponse(boolean noInit) {
        }

        private static final AreaListResponse defaultInstance;

        public static AreaListResponse getDefaultInstance() {
            return defaultInstance;
        }

        public AreaListResponse getDefaultInstanceForType() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
                getDescriptor() {
            return com.bw.application.message.AreaList.internal_static_message_AreaListResponse_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
                internalGetFieldAccessorTable() {
            return com.bw.application.message.AreaList.internal_static_message_AreaListResponse_fieldAccessorTable;
        }

        public interface AreaDataOrBuilder
                extends com.google.protobuf.MessageOrBuilder {

            // optional int32 area_id = 1;
            boolean hasAreaId();

            int getAreaId();

            // optional string area_name = 2;
            boolean hasAreaName();

            String getAreaName();

            // optional int32 status = 3;
            boolean hasStatus();

            int getStatus();
        }

        public static final class AreaData extends
                com.google.protobuf.GeneratedMessage
                implements AreaDataOrBuilder {
            // Use AreaData.newBuilder() to construct.

            private AreaData(Builder builder) {
                super(builder);
            }

            private AreaData(boolean noInit) {
            }

            private static final AreaData defaultInstance;

            public static AreaData getDefaultInstance() {
                return defaultInstance;
            }

            public AreaData getDefaultInstanceForType() {
                return defaultInstance;
            }

            public static final com.google.protobuf.Descriptors.Descriptor
                    getDescriptor() {
                return com.bw.application.message.AreaList.internal_static_message_AreaListResponse_AreaData_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
                    internalGetFieldAccessorTable() {
                return com.bw.application.message.AreaList.internal_static_message_AreaListResponse_AreaData_fieldAccessorTable;
            }

            private int bitField0_;
            // optional int32 area_id = 1;
            public static final int AREA_ID_FIELD_NUMBER = 1;
            private int areaId_;

            public boolean hasAreaId() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            public int getAreaId() {
                return areaId_;
            }

            // optional string area_name = 2;
            public static final int AREA_NAME_FIELD_NUMBER = 2;
            private java.lang.Object areaName_;

            public boolean hasAreaName() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            public String getAreaName() {
                java.lang.Object ref = areaName_;
                if (ref instanceof String) {
                    return (String) ref;
                } else {
                    com.google.protobuf.ByteString bs
                            = (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                        areaName_ = s;
                    }
                    return s;
                }
            }

            private com.google.protobuf.ByteString getAreaNameBytes() {
                java.lang.Object ref = areaName_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b
                            = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                    areaName_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            // optional int32 status = 3;
            public static final int STATUS_FIELD_NUMBER = 3;
            private int status_;

            public boolean hasStatus() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            public int getStatus() {
                return status_;
            }

            private void initFields() {
                areaId_ = 0;
                areaName_ = "";
                status_ = 0;
            }
            private byte memoizedIsInitialized = -1;

            public final boolean isInitialized() {
                byte isInitialized = memoizedIsInitialized;
                if (isInitialized != -1) {
                    return isInitialized == 1;
                }

                memoizedIsInitialized = 1;
                return true;
            }

            public void writeTo(com.google.protobuf.CodedOutputStream output)
                    throws java.io.IOException {
                getSerializedSize();
                if (((bitField0_ & 0x00000001) == 0x00000001)) {
                    output.writeInt32(1, areaId_);
                }
                if (((bitField0_ & 0x00000002) == 0x00000002)) {
                    output.writeBytes(2, getAreaNameBytes());
                }
                if (((bitField0_ & 0x00000004) == 0x00000004)) {
                    output.writeInt32(3, status_);
                }
                getUnknownFields().writeTo(output);
            }

            private int memoizedSerializedSize = -1;

            public int getSerializedSize() {
                int size = memoizedSerializedSize;
                if (size != -1) {
                    return size;
                }

                size = 0;
                if (((bitField0_ & 0x00000001) == 0x00000001)) {
                    size += com.google.protobuf.CodedOutputStream
                            .computeInt32Size(1, areaId_);
                }
                if (((bitField0_ & 0x00000002) == 0x00000002)) {
                    size += com.google.protobuf.CodedOutputStream
                            .computeBytesSize(2, getAreaNameBytes());
                }
                if (((bitField0_ & 0x00000004) == 0x00000004)) {
                    size += com.google.protobuf.CodedOutputStream
                            .computeInt32Size(3, status_);
                }
                size += getUnknownFields().getSerializedSize();
                memoizedSerializedSize = size;
                return size;
            }

            private static final long serialVersionUID = 0L;

            @java.lang.Override
            protected java.lang.Object writeReplace()
                    throws java.io.ObjectStreamException {
                return super.writeReplace();
            }

            public static com.bw.application.message.AreaList.AreaListResponse.AreaData parseFrom(
                    com.google.protobuf.ByteString data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return newBuilder().mergeFrom(data).buildParsed();
            }

            public static com.bw.application.message.AreaList.AreaListResponse.AreaData parseFrom(
                    com.google.protobuf.ByteString data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return newBuilder().mergeFrom(data, extensionRegistry)
                        .buildParsed();
            }

            public static com.bw.application.message.AreaList.AreaListResponse.AreaData parseFrom(byte[] data)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return newBuilder().mergeFrom(data).buildParsed();
            }

            public static com.bw.application.message.AreaList.AreaListResponse.AreaData parseFrom(
                    byte[] data,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return newBuilder().mergeFrom(data, extensionRegistry)
                        .buildParsed();
            }

            public static com.bw.application.message.AreaList.AreaListResponse.AreaData parseFrom(java.io.InputStream input)
                    throws java.io.IOException {
                return newBuilder().mergeFrom(input).buildParsed();
            }

            public static com.bw.application.message.AreaList.AreaListResponse.AreaData parseFrom(
                    java.io.InputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                return newBuilder().mergeFrom(input, extensionRegistry)
                        .buildParsed();
            }

            public static com.bw.application.message.AreaList.AreaListResponse.AreaData parseDelimitedFrom(java.io.InputStream input)
                    throws java.io.IOException {
                Builder builder = newBuilder();
                if (builder.mergeDelimitedFrom(input)) {
                    return builder.buildParsed();
                } else {
                    return null;
                }
            }

            public static com.bw.application.message.AreaList.AreaListResponse.AreaData parseDelimitedFrom(
                    java.io.InputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                Builder builder = newBuilder();
                if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
                    return builder.buildParsed();
                } else {
                    return null;
                }
            }

            public static com.bw.application.message.AreaList.AreaListResponse.AreaData parseFrom(
                    com.google.protobuf.CodedInputStream input)
                    throws java.io.IOException {
                return newBuilder().mergeFrom(input).buildParsed();
            }

            public static com.bw.application.message.AreaList.AreaListResponse.AreaData parseFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                return newBuilder().mergeFrom(input, extensionRegistry)
                        .buildParsed();
            }

            public static Builder newBuilder() {
                return Builder.create();
            }

            public Builder newBuilderForType() {
                return newBuilder();
            }

            public static Builder newBuilder(com.bw.application.message.AreaList.AreaListResponse.AreaData prototype) {
                return newBuilder().mergeFrom(prototype);
            }

            public Builder toBuilder() {
                return newBuilder(this);
            }

            @java.lang.Override
            protected Builder newBuilderForType(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                Builder builder = new Builder(parent);
                return builder;
            }

            public static final class Builder extends
                    com.google.protobuf.GeneratedMessage.Builder<Builder>
                    implements com.bw.application.message.AreaList.AreaListResponse.AreaDataOrBuilder {

                public static final com.google.protobuf.Descriptors.Descriptor
                        getDescriptor() {
                    return com.bw.application.message.AreaList.internal_static_message_AreaListResponse_AreaData_descriptor;
                }

                protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
                        internalGetFieldAccessorTable() {
                    return com.bw.application.message.AreaList.internal_static_message_AreaListResponse_AreaData_fieldAccessorTable;
                }

                // Construct using com.bw.application.message.AreaList.AreaListResponse.AreaData.newBuilder()
                private Builder() {
                    maybeForceBuilderInitialization();
                }

                private Builder(BuilderParent parent) {
                    super(parent);
                    maybeForceBuilderInitialization();
                }

                private void maybeForceBuilderInitialization() {
                    if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                    }
                }

                private static Builder create() {
                    return new Builder();
                }

                public Builder clear() {
                    super.clear();
                    areaId_ = 0;
                    bitField0_ = (bitField0_ & ~0x00000001);
                    areaName_ = "";
                    bitField0_ = (bitField0_ & ~0x00000002);
                    status_ = 0;
                    bitField0_ = (bitField0_ & ~0x00000004);
                    return this;
                }

                public Builder clone() {
                    return create().mergeFrom(buildPartial());
                }

                public com.google.protobuf.Descriptors.Descriptor
                        getDescriptorForType() {
                    return com.bw.application.message.AreaList.AreaListResponse.AreaData.getDescriptor();
                }

                public com.bw.application.message.AreaList.AreaListResponse.AreaData getDefaultInstanceForType() {
                    return com.bw.application.message.AreaList.AreaListResponse.AreaData.getDefaultInstance();
                }

                public com.bw.application.message.AreaList.AreaListResponse.AreaData build() {
                    com.bw.application.message.AreaList.AreaListResponse.AreaData result = buildPartial();
                    if (!result.isInitialized()) {
                        throw newUninitializedMessageException(result);
                    }
                    return result;
                }

                private com.bw.application.message.AreaList.AreaListResponse.AreaData buildParsed()
                        throws com.google.protobuf.InvalidProtocolBufferException {
                    com.bw.application.message.AreaList.AreaListResponse.AreaData result = buildPartial();
                    if (!result.isInitialized()) {
                        throw newUninitializedMessageException(
                                result).asInvalidProtocolBufferException();
                    }
                    return result;
                }

                public com.bw.application.message.AreaList.AreaListResponse.AreaData buildPartial() {
                    com.bw.application.message.AreaList.AreaListResponse.AreaData result = new com.bw.application.message.AreaList.AreaListResponse.AreaData(this);
                    int from_bitField0_ = bitField0_;
                    int to_bitField0_ = 0;
                    if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                        to_bitField0_ |= 0x00000001;
                    }
                    result.areaId_ = areaId_;
                    if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                        to_bitField0_ |= 0x00000002;
                    }
                    result.areaName_ = areaName_;
                    if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                        to_bitField0_ |= 0x00000004;
                    }
                    result.status_ = status_;
                    result.bitField0_ = to_bitField0_;
                    onBuilt();
                    return result;
                }

                public Builder mergeFrom(com.google.protobuf.Message other) {
                    if (other instanceof com.bw.application.message.AreaList.AreaListResponse.AreaData) {
                        return mergeFrom((com.bw.application.message.AreaList.AreaListResponse.AreaData) other);
                    } else {
                        super.mergeFrom(other);
                        return this;
                    }
                }

                public Builder mergeFrom(com.bw.application.message.AreaList.AreaListResponse.AreaData other) {
                    if (other == com.bw.application.message.AreaList.AreaListResponse.AreaData.getDefaultInstance()) {
                        return this;
                    }
                    if (other.hasAreaId()) {
                        setAreaId(other.getAreaId());
                    }
                    if (other.hasAreaName()) {
                        setAreaName(other.getAreaName());
                    }
                    if (other.hasStatus()) {
                        setStatus(other.getStatus());
                    }
                    this.mergeUnknownFields(other.getUnknownFields());
                    return this;
                }

                public final boolean isInitialized() {
                    return true;
                }

                public Builder mergeFrom(
                        com.google.protobuf.CodedInputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws java.io.IOException {
                    com.google.protobuf.UnknownFieldSet.Builder unknownFields
                            = com.google.protobuf.UnknownFieldSet.newBuilder(
                                    this.getUnknownFields());
                    while (true) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                this.setUnknownFields(unknownFields.build());
                                onChanged();
                                return this;
                            default: {
                                if (!parseUnknownField(input, unknownFields,
                                        extensionRegistry, tag)) {
                                    this.setUnknownFields(unknownFields.build());
                                    onChanged();
                                    return this;
                                }
                                break;
                            }
                            case 8: {
                                bitField0_ |= 0x00000001;
                                areaId_ = input.readInt32();
                                break;
                            }
                            case 18: {
                                bitField0_ |= 0x00000002;
                                areaName_ = input.readBytes();
                                break;
                            }
                            case 24: {
                                bitField0_ |= 0x00000004;
                                status_ = input.readInt32();
                                break;
                            }
                        }
                    }
                }

                private int bitField0_;

                // optional int32 area_id = 1;
                private int areaId_;

                public boolean hasAreaId() {
                    return ((bitField0_ & 0x00000001) == 0x00000001);
                }

                public int getAreaId() {
                    return areaId_;
                }

                public Builder setAreaId(int value) {
                    bitField0_ |= 0x00000001;
                    areaId_ = value;
                    onChanged();
                    return this;
                }

                public Builder clearAreaId() {
                    bitField0_ = (bitField0_ & ~0x00000001);
                    areaId_ = 0;
                    onChanged();
                    return this;
                }

                // optional string area_name = 2;
                private java.lang.Object areaName_ = "";

                public boolean hasAreaName() {
                    return ((bitField0_ & 0x00000002) == 0x00000002);
                }

                public String getAreaName() {
                    java.lang.Object ref = areaName_;
                    if (!(ref instanceof String)) {
                        String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                        areaName_ = s;
                        return s;
                    } else {
                        return (String) ref;
                    }
                }

                public Builder setAreaName(String value) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    bitField0_ |= 0x00000002;
                    areaName_ = value;
                    onChanged();
                    return this;
                }

                public Builder clearAreaName() {
                    bitField0_ = (bitField0_ & ~0x00000002);
                    areaName_ = getDefaultInstance().getAreaName();
                    onChanged();
                    return this;
                }

                void setAreaName(com.google.protobuf.ByteString value) {
                    bitField0_ |= 0x00000002;
                    areaName_ = value;
                    onChanged();
                }

                // optional int32 status = 3;
                private int status_;

                public boolean hasStatus() {
                    return ((bitField0_ & 0x00000004) == 0x00000004);
                }

                public int getStatus() {
                    return status_;
                }

                public Builder setStatus(int value) {
                    bitField0_ |= 0x00000004;
                    status_ = value;
                    onChanged();
                    return this;
                }

                public Builder clearStatus() {
                    bitField0_ = (bitField0_ & ~0x00000004);
                    status_ = 0;
                    onChanged();
                    return this;
                }

                // @@protoc_insertion_point(builder_scope:message.AreaListResponse.AreaData)
            }

            static {
                defaultInstance = new AreaData(true);
                defaultInstance.initFields();
            }

            // @@protoc_insertion_point(class_scope:message.AreaListResponse.AreaData)
        }

        private int bitField0_;
        // optional sint32 result = 1;
        public static final int RESULT_FIELD_NUMBER = 1;
        private int result_;

        public boolean hasResult() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        public int getResult() {
            return result_;
        }

        // optional string info = 2;
        public static final int INFO_FIELD_NUMBER = 2;
        private java.lang.Object info_;

        public boolean hasInfo() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        public String getInfo() {
            java.lang.Object ref = info_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs
                        = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    info_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getInfoBytes() {
            java.lang.Object ref = info_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b
                        = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                info_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // repeated .message.AreaListResponse.AreaData areaDataList = 3;
        public static final int AREADATALIST_FIELD_NUMBER = 3;
        private java.util.List<com.bw.application.message.AreaList.AreaListResponse.AreaData> areaDataList_;

        public java.util.List<com.bw.application.message.AreaList.AreaListResponse.AreaData> getAreaDataListList() {
            return areaDataList_;
        }

        public java.util.List<? extends com.bw.application.message.AreaList.AreaListResponse.AreaDataOrBuilder>
                getAreaDataListOrBuilderList() {
            return areaDataList_;
        }

        public int getAreaDataListCount() {
            return areaDataList_.size();
        }

        public com.bw.application.message.AreaList.AreaListResponse.AreaData getAreaDataList(int index) {
            return areaDataList_.get(index);
        }

        public com.bw.application.message.AreaList.AreaListResponse.AreaDataOrBuilder getAreaDataListOrBuilder(
                int index) {
            return areaDataList_.get(index);
        }

        private void initFields() {
            result_ = 0;
            info_ = "";
            areaDataList_ = java.util.Collections.emptyList();
        }
        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) {
                return isInitialized == 1;
            }

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeSInt32(1, result_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(2, getInfoBytes());
            }
            for (int i = 0; i < areaDataList_.size(); i++) {
                output.writeMessage(3, areaDataList_.get(i));
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) {
                return size;
            }

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeSInt32Size(1, result_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, getInfoBytes());
            }
            for (int i = 0; i < areaDataList_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(3, areaDataList_.get(i));
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static com.bw.application.message.AreaList.AreaListResponse parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static com.bw.application.message.AreaList.AreaListResponse parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static com.bw.application.message.AreaList.AreaListResponse parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static com.bw.application.message.AreaList.AreaListResponse parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static com.bw.application.message.AreaList.AreaListResponse parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static com.bw.application.message.AreaList.AreaListResponse parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static com.bw.application.message.AreaList.AreaListResponse parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static com.bw.application.message.AreaList.AreaListResponse parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static com.bw.application.message.AreaList.AreaListResponse parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static com.bw.application.message.AreaList.AreaListResponse parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(com.bw.application.message.AreaList.AreaListResponse prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements com.bw.application.message.AreaList.AreaListResponseOrBuilder {

            public static final com.google.protobuf.Descriptors.Descriptor
                    getDescriptor() {
                return com.bw.application.message.AreaList.internal_static_message_AreaListResponse_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
                    internalGetFieldAccessorTable() {
                return com.bw.application.message.AreaList.internal_static_message_AreaListResponse_fieldAccessorTable;
            }

            // Construct using com.bw.application.message.AreaList.AreaListResponse.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                    getAreaDataListFieldBuilder();
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                result_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                info_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                if (areaDataListBuilder_ == null) {
                    areaDataList_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000004);
                } else {
                    areaDataListBuilder_.clear();
                }
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
                    getDescriptorForType() {
                return com.bw.application.message.AreaList.AreaListResponse.getDescriptor();
            }

            public com.bw.application.message.AreaList.AreaListResponse getDefaultInstanceForType() {
                return com.bw.application.message.AreaList.AreaListResponse.getDefaultInstance();
            }

            public com.bw.application.message.AreaList.AreaListResponse build() {
                com.bw.application.message.AreaList.AreaListResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            private com.bw.application.message.AreaList.AreaListResponse buildParsed()
                    throws com.google.protobuf.InvalidProtocolBufferException {
                com.bw.application.message.AreaList.AreaListResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(
                            result).asInvalidProtocolBufferException();
                }
                return result;
            }

            public com.bw.application.message.AreaList.AreaListResponse buildPartial() {
                com.bw.application.message.AreaList.AreaListResponse result = new com.bw.application.message.AreaList.AreaListResponse(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.result_ = result_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.info_ = info_;
                if (areaDataListBuilder_ == null) {
                    if (((bitField0_ & 0x00000004) == 0x00000004)) {
                        areaDataList_ = java.util.Collections.unmodifiableList(areaDataList_);
                        bitField0_ = (bitField0_ & ~0x00000004);
                    }
                    result.areaDataList_ = areaDataList_;
                } else {
                    result.areaDataList_ = areaDataListBuilder_.build();
                }
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.bw.application.message.AreaList.AreaListResponse) {
                    return mergeFrom((com.bw.application.message.AreaList.AreaListResponse) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.bw.application.message.AreaList.AreaListResponse other) {
                if (other == com.bw.application.message.AreaList.AreaListResponse.getDefaultInstance()) {
                    return this;
                }
                if (other.hasResult()) {
                    setResult(other.getResult());
                }
                if (other.hasInfo()) {
                    setInfo(other.getInfo());
                }
                if (areaDataListBuilder_ == null) {
                    if (!other.areaDataList_.isEmpty()) {
                        if (areaDataList_.isEmpty()) {
                            areaDataList_ = other.areaDataList_;
                            bitField0_ = (bitField0_ & ~0x00000004);
                        } else {
                            ensureAreaDataListIsMutable();
                            areaDataList_.addAll(other.areaDataList_);
                        }
                        onChanged();
                    }
                } else if (!other.areaDataList_.isEmpty()) {
                    if (areaDataListBuilder_.isEmpty()) {
                        areaDataListBuilder_.dispose();
                        areaDataListBuilder_ = null;
                        areaDataList_ = other.areaDataList_;
                        bitField0_ = (bitField0_ & ~0x00000004);
                        areaDataListBuilder_
                                = com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders
                                        ? getAreaDataListFieldBuilder() : null;
                    } else {
                        areaDataListBuilder_.addAllMessages(other.areaDataList_);
                    }
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.google.protobuf.UnknownFieldSet.Builder unknownFields
                        = com.google.protobuf.UnknownFieldSet.newBuilder(
                                this.getUnknownFields());
                while (true) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            this.setUnknownFields(unknownFields.build());
                            onChanged();
                            return this;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                this.setUnknownFields(unknownFields.build());
                                onChanged();
                                return this;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            result_ = input.readSInt32();
                            break;
                        }
                        case 18: {
                            bitField0_ |= 0x00000002;
                            info_ = input.readBytes();
                            break;
                        }
                        case 26: {
                            com.bw.application.message.AreaList.AreaListResponse.AreaData.Builder subBuilder = com.bw.application.message.AreaList.AreaListResponse.AreaData.newBuilder();
                            input.readMessage(subBuilder, extensionRegistry);
                            addAreaDataList(subBuilder.buildPartial());
                            break;
                        }
                    }
                }
            }

            private int bitField0_;

            // optional sint32 result = 1;
            private int result_;

            public boolean hasResult() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            public int getResult() {
                return result_;
            }

            public Builder setResult(int value) {
                bitField0_ |= 0x00000001;
                result_ = value;
                onChanged();
                return this;
            }

            public Builder clearResult() {
                bitField0_ = (bitField0_ & ~0x00000001);
                result_ = 0;
                onChanged();
                return this;
            }

            // optional string info = 2;
            private java.lang.Object info_ = "";

            public boolean hasInfo() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            public String getInfo() {
                java.lang.Object ref = info_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    info_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            public Builder setInfo(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                info_ = value;
                onChanged();
                return this;
            }

            public Builder clearInfo() {
                bitField0_ = (bitField0_ & ~0x00000002);
                info_ = getDefaultInstance().getInfo();
                onChanged();
                return this;
            }

            void setInfo(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000002;
                info_ = value;
                onChanged();
            }

            // repeated .message.AreaListResponse.AreaData areaDataList = 3;
            private java.util.List<com.bw.application.message.AreaList.AreaListResponse.AreaData> areaDataList_
                    = java.util.Collections.emptyList();

            private void ensureAreaDataListIsMutable() {
                if (!((bitField0_ & 0x00000004) == 0x00000004)) {
                    areaDataList_ = new java.util.ArrayList<com.bw.application.message.AreaList.AreaListResponse.AreaData>(areaDataList_);
                    bitField0_ |= 0x00000004;
                }
            }

            private com.google.protobuf.RepeatedFieldBuilder<
          com.bw.application.message.AreaList.AreaListResponse.AreaData, com.bw.application.message.AreaList.AreaListResponse.AreaData.Builder, com.bw.application.message.AreaList.AreaListResponse.AreaDataOrBuilder> areaDataListBuilder_;

            public java.util.List<com.bw.application.message.AreaList.AreaListResponse.AreaData> getAreaDataListList() {
                if (areaDataListBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(areaDataList_);
                } else {
                    return areaDataListBuilder_.getMessageList();
                }
            }

            public int getAreaDataListCount() {
                if (areaDataListBuilder_ == null) {
                    return areaDataList_.size();
                } else {
                    return areaDataListBuilder_.getCount();
                }
            }

            public com.bw.application.message.AreaList.AreaListResponse.AreaData getAreaDataList(int index) {
                if (areaDataListBuilder_ == null) {
                    return areaDataList_.get(index);
                } else {
                    return areaDataListBuilder_.getMessage(index);
                }
            }

            public Builder setAreaDataList(
                    int index, com.bw.application.message.AreaList.AreaListResponse.AreaData value) {
                if (areaDataListBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureAreaDataListIsMutable();
                    areaDataList_.set(index, value);
                    onChanged();
                } else {
                    areaDataListBuilder_.setMessage(index, value);
                }
                return this;
            }

            public Builder setAreaDataList(
                    int index, com.bw.application.message.AreaList.AreaListResponse.AreaData.Builder builderForValue) {
                if (areaDataListBuilder_ == null) {
                    ensureAreaDataListIsMutable();
                    areaDataList_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    areaDataListBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }

            public Builder addAreaDataList(com.bw.application.message.AreaList.AreaListResponse.AreaData value) {
                if (areaDataListBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureAreaDataListIsMutable();
                    areaDataList_.add(value);
                    onChanged();
                } else {
                    areaDataListBuilder_.addMessage(value);
                }
                return this;
            }

            public Builder addAreaDataList(
                    int index, com.bw.application.message.AreaList.AreaListResponse.AreaData value) {
                if (areaDataListBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureAreaDataListIsMutable();
                    areaDataList_.add(index, value);
                    onChanged();
                } else {
                    areaDataListBuilder_.addMessage(index, value);
                }
                return this;
            }

            public Builder addAreaDataList(
                    com.bw.application.message.AreaList.AreaListResponse.AreaData.Builder builderForValue) {
                if (areaDataListBuilder_ == null) {
                    ensureAreaDataListIsMutable();
                    areaDataList_.add(builderForValue.build());
                    onChanged();
                } else {
                    areaDataListBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }

            public Builder addAreaDataList(
                    int index, com.bw.application.message.AreaList.AreaListResponse.AreaData.Builder builderForValue) {
                if (areaDataListBuilder_ == null) {
                    ensureAreaDataListIsMutable();
                    areaDataList_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    areaDataListBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }

            public Builder addAllAreaDataList(
                    java.lang.Iterable<? extends com.bw.application.message.AreaList.AreaListResponse.AreaData> values) {
                if (areaDataListBuilder_ == null) {
                    ensureAreaDataListIsMutable();
                    super.addAll(values, areaDataList_);
                    onChanged();
                } else {
                    areaDataListBuilder_.addAllMessages(values);
                }
                return this;
            }

            public Builder clearAreaDataList() {
                if (areaDataListBuilder_ == null) {
                    areaDataList_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000004);
                    onChanged();
                } else {
                    areaDataListBuilder_.clear();
                }
                return this;
            }

            public Builder removeAreaDataList(int index) {
                if (areaDataListBuilder_ == null) {
                    ensureAreaDataListIsMutable();
                    areaDataList_.remove(index);
                    onChanged();
                } else {
                    areaDataListBuilder_.remove(index);
                }
                return this;
            }

            public com.bw.application.message.AreaList.AreaListResponse.AreaData.Builder getAreaDataListBuilder(
                    int index) {
                return getAreaDataListFieldBuilder().getBuilder(index);
            }

            public com.bw.application.message.AreaList.AreaListResponse.AreaDataOrBuilder getAreaDataListOrBuilder(
                    int index) {
                if (areaDataListBuilder_ == null) {
                    return areaDataList_.get(index);
                } else {
                    return areaDataListBuilder_.getMessageOrBuilder(index);
                }
            }

            public java.util.List<? extends com.bw.application.message.AreaList.AreaListResponse.AreaDataOrBuilder>
                    getAreaDataListOrBuilderList() {
                if (areaDataListBuilder_ != null) {
                    return areaDataListBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(areaDataList_);
                }
            }

            public com.bw.application.message.AreaList.AreaListResponse.AreaData.Builder addAreaDataListBuilder() {
                return getAreaDataListFieldBuilder().addBuilder(
                        com.bw.application.message.AreaList.AreaListResponse.AreaData.getDefaultInstance());
            }

            public com.bw.application.message.AreaList.AreaListResponse.AreaData.Builder addAreaDataListBuilder(
                    int index) {
                return getAreaDataListFieldBuilder().addBuilder(
                        index, com.bw.application.message.AreaList.AreaListResponse.AreaData.getDefaultInstance());
            }

            public java.util.List<com.bw.application.message.AreaList.AreaListResponse.AreaData.Builder>
                    getAreaDataListBuilderList() {
                return getAreaDataListFieldBuilder().getBuilderList();
            }

            private com.google.protobuf.RepeatedFieldBuilder<
          com.bw.application.message.AreaList.AreaListResponse.AreaData, com.bw.application.message.AreaList.AreaListResponse.AreaData.Builder, com.bw.application.message.AreaList.AreaListResponse.AreaDataOrBuilder>
                    getAreaDataListFieldBuilder() {
                if (areaDataListBuilder_ == null) {
                    areaDataListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.bw.application.message.AreaList.AreaListResponse.AreaData, com.bw.application.message.AreaList.AreaListResponse.AreaData.Builder, com.bw.application.message.AreaList.AreaListResponse.AreaDataOrBuilder>(
                            areaDataList_,
                            ((bitField0_ & 0x00000004) == 0x00000004),
                            getParentForChildren(),
                            isClean());
                    areaDataList_ = null;
                }
                return areaDataListBuilder_;
            }

            // @@protoc_insertion_point(builder_scope:message.AreaListResponse)
        }

        static {
            defaultInstance = new AreaListResponse(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:message.AreaListResponse)
    }

    private static com.google.protobuf.Descriptors.Descriptor internal_static_message_AreaListRequest_descriptor;
    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_message_AreaListRequest_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.Descriptor internal_static_message_AreaListResponse_descriptor;
    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_message_AreaListResponse_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.Descriptor internal_static_message_AreaListResponse_AreaData_descriptor;
    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_message_AreaListResponse_AreaData_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
            getDescriptor() {
        return descriptor;
    }
    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

    static {
        java.lang.String[] descriptorData = {
            "\n\016AreaList.proto\022\007message\"&\n\017AreaListReq"
            + "uest\022\023\n\013mac_address\030\001 \002(\t\"\252\001\n\020AreaListRe"
            + "sponse\022\016\n\006result\030\001 \001(\021\022\014\n\004info\030\002 \001(\t\0228\n\014"
            + "areaDataList\030\003 \003(\0132\".message.AreaListRes"
            + "ponse.AreaData\032>\n\010AreaData\022\017\n\007area_id\030\001 "
            + "\001(\005\022\021\n\tarea_name\030\002 \001(\t\022\016\n\006status\030\003 \001(\005B&"
            + "\n\032com.bw.application.messageB\010AreaList"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner
                = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
            public com.google.protobuf.ExtensionRegistry assignDescriptors(
                    com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                internal_static_message_AreaListRequest_descriptor
                        = getDescriptor().getMessageTypes().get(0);
                internal_static_message_AreaListRequest_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                        internal_static_message_AreaListRequest_descriptor,
                        new java.lang.String[]{"MacAddress",},
                        com.bw.application.message.AreaList.AreaListRequest.class,
                        com.bw.application.message.AreaList.AreaListRequest.Builder.class);
                internal_static_message_AreaListResponse_descriptor
                        = getDescriptor().getMessageTypes().get(1);
                internal_static_message_AreaListResponse_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                        internal_static_message_AreaListResponse_descriptor,
                        new java.lang.String[]{"Result", "Info", "AreaDataList",},
                        com.bw.application.message.AreaList.AreaListResponse.class,
                        com.bw.application.message.AreaList.AreaListResponse.Builder.class);
                internal_static_message_AreaListResponse_AreaData_descriptor
                        = internal_static_message_AreaListResponse_descriptor.getNestedTypes().get(0);
                internal_static_message_AreaListResponse_AreaData_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                        internal_static_message_AreaListResponse_AreaData_descriptor,
                        new java.lang.String[]{"AreaId", "AreaName", "Status",},
                        com.bw.application.message.AreaList.AreaListResponse.AreaData.class,
                        com.bw.application.message.AreaList.AreaListResponse.AreaData.Builder.class);
                return null;
            }
        };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{}, assigner);
    }

    // @@protoc_insertion_point(outer_class_scope)
}
