// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UUIDsSelfBuilder.proto
package com.bw.application.message;

public final class UUIDsSelfBuilder {

    private UUIDsSelfBuilder() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }

    public interface CreateUUIDRequestOrBuilder
            extends com.google.protobuf.MessageOrBuilder {

        // optional string serverNumber = 1;
        boolean hasServerNumber();

        String getServerNumber();

        // optional string macAddress = 2;
        boolean hasMacAddress();

        String getMacAddress();

        // optional int32 area_id = 3;
        boolean hasAreaId();

        int getAreaId();
    }

    public static final class CreateUUIDRequest extends
            com.google.protobuf.GeneratedMessage
            implements CreateUUIDRequestOrBuilder {
        // Use CreateUUIDRequest.newBuilder() to construct.

        private CreateUUIDRequest(Builder builder) {
            super(builder);
        }

        private CreateUUIDRequest(boolean noInit) {
        }

        private static final CreateUUIDRequest defaultInstance;

        public static CreateUUIDRequest getDefaultInstance() {
            return defaultInstance;
        }

        public CreateUUIDRequest getDefaultInstanceForType() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
                getDescriptor() {
            return com.bw.application.message.UUIDsSelfBuilder.internal_static_message_CreateUUIDRequest_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
                internalGetFieldAccessorTable() {
            return com.bw.application.message.UUIDsSelfBuilder.internal_static_message_CreateUUIDRequest_fieldAccessorTable;
        }

        private int bitField0_;
        // optional string serverNumber = 1;
        public static final int SERVERNUMBER_FIELD_NUMBER = 1;
        private java.lang.Object serverNumber_;

        public boolean hasServerNumber() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        public String getServerNumber() {
            java.lang.Object ref = serverNumber_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs
                        = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    serverNumber_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getServerNumberBytes() {
            java.lang.Object ref = serverNumber_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b
                        = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                serverNumber_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // optional string macAddress = 2;
        public static final int MACADDRESS_FIELD_NUMBER = 2;
        private java.lang.Object macAddress_;

        public boolean hasMacAddress() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        public String getMacAddress() {
            java.lang.Object ref = macAddress_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs
                        = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    macAddress_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getMacAddressBytes() {
            java.lang.Object ref = macAddress_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b
                        = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                macAddress_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // optional int32 area_id = 3;
        public static final int AREA_ID_FIELD_NUMBER = 3;
        private int areaId_;

        public boolean hasAreaId() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        public int getAreaId() {
            return areaId_;
        }

        private void initFields() {
            serverNumber_ = "";
            macAddress_ = "";
            areaId_ = 0;
        }
        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) {
                return isInitialized == 1;
            }

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(1, getServerNumberBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(2, getMacAddressBytes());
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeInt32(3, areaId_);
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) {
                return size;
            }

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(1, getServerNumberBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, getMacAddressBytes());
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(3, areaId_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static com.bw.application.message.UUIDsSelfBuilder.CreateUUIDRequest parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static com.bw.application.message.UUIDsSelfBuilder.CreateUUIDRequest parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static com.bw.application.message.UUIDsSelfBuilder.CreateUUIDRequest parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static com.bw.application.message.UUIDsSelfBuilder.CreateUUIDRequest parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static com.bw.application.message.UUIDsSelfBuilder.CreateUUIDRequest parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static com.bw.application.message.UUIDsSelfBuilder.CreateUUIDRequest parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static com.bw.application.message.UUIDsSelfBuilder.CreateUUIDRequest parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static com.bw.application.message.UUIDsSelfBuilder.CreateUUIDRequest parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static com.bw.application.message.UUIDsSelfBuilder.CreateUUIDRequest parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static com.bw.application.message.UUIDsSelfBuilder.CreateUUIDRequest parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(com.bw.application.message.UUIDsSelfBuilder.CreateUUIDRequest prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements com.bw.application.message.UUIDsSelfBuilder.CreateUUIDRequestOrBuilder {

            public static final com.google.protobuf.Descriptors.Descriptor
                    getDescriptor() {
                return com.bw.application.message.UUIDsSelfBuilder.internal_static_message_CreateUUIDRequest_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
                    internalGetFieldAccessorTable() {
                return com.bw.application.message.UUIDsSelfBuilder.internal_static_message_CreateUUIDRequest_fieldAccessorTable;
            }

            // Construct using com.bw.application.message.UUIDsSelfBuilder.CreateUUIDRequest.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                serverNumber_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                macAddress_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                areaId_ = 0;
                bitField0_ = (bitField0_ & ~0x00000004);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
                    getDescriptorForType() {
                return com.bw.application.message.UUIDsSelfBuilder.CreateUUIDRequest.getDescriptor();
            }

            public com.bw.application.message.UUIDsSelfBuilder.CreateUUIDRequest getDefaultInstanceForType() {
                return com.bw.application.message.UUIDsSelfBuilder.CreateUUIDRequest.getDefaultInstance();
            }

            public com.bw.application.message.UUIDsSelfBuilder.CreateUUIDRequest build() {
                com.bw.application.message.UUIDsSelfBuilder.CreateUUIDRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            private com.bw.application.message.UUIDsSelfBuilder.CreateUUIDRequest buildParsed()
                    throws com.google.protobuf.InvalidProtocolBufferException {
                com.bw.application.message.UUIDsSelfBuilder.CreateUUIDRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(
                            result).asInvalidProtocolBufferException();
                }
                return result;
            }

            public com.bw.application.message.UUIDsSelfBuilder.CreateUUIDRequest buildPartial() {
                com.bw.application.message.UUIDsSelfBuilder.CreateUUIDRequest result = new com.bw.application.message.UUIDsSelfBuilder.CreateUUIDRequest(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.serverNumber_ = serverNumber_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.macAddress_ = macAddress_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.areaId_ = areaId_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.bw.application.message.UUIDsSelfBuilder.CreateUUIDRequest) {
                    return mergeFrom((com.bw.application.message.UUIDsSelfBuilder.CreateUUIDRequest) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.bw.application.message.UUIDsSelfBuilder.CreateUUIDRequest other) {
                if (other == com.bw.application.message.UUIDsSelfBuilder.CreateUUIDRequest.getDefaultInstance()) {
                    return this;
                }
                if (other.hasServerNumber()) {
                    setServerNumber(other.getServerNumber());
                }
                if (other.hasMacAddress()) {
                    setMacAddress(other.getMacAddress());
                }
                if (other.hasAreaId()) {
                    setAreaId(other.getAreaId());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.google.protobuf.UnknownFieldSet.Builder unknownFields
                        = com.google.protobuf.UnknownFieldSet.newBuilder(
                                this.getUnknownFields());
                while (true) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            this.setUnknownFields(unknownFields.build());
                            onChanged();
                            return this;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                this.setUnknownFields(unknownFields.build());
                                onChanged();
                                return this;
                            }
                            break;
                        }
                        case 10: {
                            bitField0_ |= 0x00000001;
                            serverNumber_ = input.readBytes();
                            break;
                        }
                        case 18: {
                            bitField0_ |= 0x00000002;
                            macAddress_ = input.readBytes();
                            break;
                        }
                        case 24: {
                            bitField0_ |= 0x00000004;
                            areaId_ = input.readInt32();
                            break;
                        }
                    }
                }
            }

            private int bitField0_;

            // optional string serverNumber = 1;
            private java.lang.Object serverNumber_ = "";

            public boolean hasServerNumber() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            public String getServerNumber() {
                java.lang.Object ref = serverNumber_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    serverNumber_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            public Builder setServerNumber(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                serverNumber_ = value;
                onChanged();
                return this;
            }

            public Builder clearServerNumber() {
                bitField0_ = (bitField0_ & ~0x00000001);
                serverNumber_ = getDefaultInstance().getServerNumber();
                onChanged();
                return this;
            }

            void setServerNumber(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000001;
                serverNumber_ = value;
                onChanged();
            }

            // optional string macAddress = 2;
            private java.lang.Object macAddress_ = "";

            public boolean hasMacAddress() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            public String getMacAddress() {
                java.lang.Object ref = macAddress_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    macAddress_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            public Builder setMacAddress(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                macAddress_ = value;
                onChanged();
                return this;
            }

            public Builder clearMacAddress() {
                bitField0_ = (bitField0_ & ~0x00000002);
                macAddress_ = getDefaultInstance().getMacAddress();
                onChanged();
                return this;
            }

            void setMacAddress(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000002;
                macAddress_ = value;
                onChanged();
            }

            // optional int32 area_id = 3;
            private int areaId_;

            public boolean hasAreaId() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            public int getAreaId() {
                return areaId_;
            }

            public Builder setAreaId(int value) {
                bitField0_ |= 0x00000004;
                areaId_ = value;
                onChanged();
                return this;
            }

            public Builder clearAreaId() {
                bitField0_ = (bitField0_ & ~0x00000004);
                areaId_ = 0;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:message.CreateUUIDRequest)
        }

        static {
            defaultInstance = new CreateUUIDRequest(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:message.CreateUUIDRequest)
    }

    public interface CreateUUIDResponseOrBuilder
            extends com.google.protobuf.MessageOrBuilder {

        // optional sint32 result = 1;
        boolean hasResult();

        int getResult();

        // optional string info = 2;
        boolean hasInfo();

        String getInfo();

        // optional int64 uuid = 3;
        boolean hasUuid();

        long getUuid();

        // optional string macAddress = 4;
        boolean hasMacAddress();

        String getMacAddress();

        // optional int32 area_id = 5;
        boolean hasAreaId();

        int getAreaId();
    }

    public static final class CreateUUIDResponse extends
            com.google.protobuf.GeneratedMessage
            implements CreateUUIDResponseOrBuilder {
        // Use CreateUUIDResponse.newBuilder() to construct.

        private CreateUUIDResponse(Builder builder) {
            super(builder);
        }

        private CreateUUIDResponse(boolean noInit) {
        }

        private static final CreateUUIDResponse defaultInstance;

        public static CreateUUIDResponse getDefaultInstance() {
            return defaultInstance;
        }

        public CreateUUIDResponse getDefaultInstanceForType() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
                getDescriptor() {
            return com.bw.application.message.UUIDsSelfBuilder.internal_static_message_CreateUUIDResponse_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
                internalGetFieldAccessorTable() {
            return com.bw.application.message.UUIDsSelfBuilder.internal_static_message_CreateUUIDResponse_fieldAccessorTable;
        }

        private int bitField0_;
        // optional sint32 result = 1;
        public static final int RESULT_FIELD_NUMBER = 1;
        private int result_;

        public boolean hasResult() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        public int getResult() {
            return result_;
        }

        // optional string info = 2;
        public static final int INFO_FIELD_NUMBER = 2;
        private java.lang.Object info_;

        public boolean hasInfo() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        public String getInfo() {
            java.lang.Object ref = info_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs
                        = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    info_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getInfoBytes() {
            java.lang.Object ref = info_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b
                        = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                info_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // optional int64 uuid = 3;
        public static final int UUID_FIELD_NUMBER = 3;
        private long uuid_;

        public boolean hasUuid() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        public long getUuid() {
            return uuid_;
        }

        // optional string macAddress = 4;
        public static final int MACADDRESS_FIELD_NUMBER = 4;
        private java.lang.Object macAddress_;

        public boolean hasMacAddress() {
            return ((bitField0_ & 0x00000008) == 0x00000008);
        }

        public String getMacAddress() {
            java.lang.Object ref = macAddress_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs
                        = (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    macAddress_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getMacAddressBytes() {
            java.lang.Object ref = macAddress_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b
                        = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                macAddress_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // optional int32 area_id = 5;
        public static final int AREA_ID_FIELD_NUMBER = 5;
        private int areaId_;

        public boolean hasAreaId() {
            return ((bitField0_ & 0x00000010) == 0x00000010);
        }

        public int getAreaId() {
            return areaId_;
        }

        private void initFields() {
            result_ = 0;
            info_ = "";
            uuid_ = 0L;
            macAddress_ = "";
            areaId_ = 0;
        }
        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) {
                return isInitialized == 1;
            }

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeSInt32(1, result_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(2, getInfoBytes());
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeInt64(3, uuid_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                output.writeBytes(4, getMacAddressBytes());
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                output.writeInt32(5, areaId_);
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) {
                return size;
            }

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeSInt32Size(1, result_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, getInfoBytes());
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(3, uuid_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(4, getMacAddressBytes());
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(5, areaId_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static com.bw.application.message.UUIDsSelfBuilder.CreateUUIDResponse parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static com.bw.application.message.UUIDsSelfBuilder.CreateUUIDResponse parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static com.bw.application.message.UUIDsSelfBuilder.CreateUUIDResponse parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static com.bw.application.message.UUIDsSelfBuilder.CreateUUIDResponse parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static com.bw.application.message.UUIDsSelfBuilder.CreateUUIDResponse parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static com.bw.application.message.UUIDsSelfBuilder.CreateUUIDResponse parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static com.bw.application.message.UUIDsSelfBuilder.CreateUUIDResponse parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static com.bw.application.message.UUIDsSelfBuilder.CreateUUIDResponse parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static com.bw.application.message.UUIDsSelfBuilder.CreateUUIDResponse parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static com.bw.application.message.UUIDsSelfBuilder.CreateUUIDResponse parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(com.bw.application.message.UUIDsSelfBuilder.CreateUUIDResponse prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements com.bw.application.message.UUIDsSelfBuilder.CreateUUIDResponseOrBuilder {

            public static final com.google.protobuf.Descriptors.Descriptor
                    getDescriptor() {
                return com.bw.application.message.UUIDsSelfBuilder.internal_static_message_CreateUUIDResponse_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
                    internalGetFieldAccessorTable() {
                return com.bw.application.message.UUIDsSelfBuilder.internal_static_message_CreateUUIDResponse_fieldAccessorTable;
            }

            // Construct using com.bw.application.message.UUIDsSelfBuilder.CreateUUIDResponse.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                result_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                info_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                uuid_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000004);
                macAddress_ = "";
                bitField0_ = (bitField0_ & ~0x00000008);
                areaId_ = 0;
                bitField0_ = (bitField0_ & ~0x00000010);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
                    getDescriptorForType() {
                return com.bw.application.message.UUIDsSelfBuilder.CreateUUIDResponse.getDescriptor();
            }

            public com.bw.application.message.UUIDsSelfBuilder.CreateUUIDResponse getDefaultInstanceForType() {
                return com.bw.application.message.UUIDsSelfBuilder.CreateUUIDResponse.getDefaultInstance();
            }

            public com.bw.application.message.UUIDsSelfBuilder.CreateUUIDResponse build() {
                com.bw.application.message.UUIDsSelfBuilder.CreateUUIDResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            private com.bw.application.message.UUIDsSelfBuilder.CreateUUIDResponse buildParsed()
                    throws com.google.protobuf.InvalidProtocolBufferException {
                com.bw.application.message.UUIDsSelfBuilder.CreateUUIDResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(
                            result).asInvalidProtocolBufferException();
                }
                return result;
            }

            public com.bw.application.message.UUIDsSelfBuilder.CreateUUIDResponse buildPartial() {
                com.bw.application.message.UUIDsSelfBuilder.CreateUUIDResponse result = new com.bw.application.message.UUIDsSelfBuilder.CreateUUIDResponse(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.result_ = result_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.info_ = info_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.uuid_ = uuid_;
                if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
                    to_bitField0_ |= 0x00000008;
                }
                result.macAddress_ = macAddress_;
                if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
                    to_bitField0_ |= 0x00000010;
                }
                result.areaId_ = areaId_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.bw.application.message.UUIDsSelfBuilder.CreateUUIDResponse) {
                    return mergeFrom((com.bw.application.message.UUIDsSelfBuilder.CreateUUIDResponse) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.bw.application.message.UUIDsSelfBuilder.CreateUUIDResponse other) {
                if (other == com.bw.application.message.UUIDsSelfBuilder.CreateUUIDResponse.getDefaultInstance()) {
                    return this;
                }
                if (other.hasResult()) {
                    setResult(other.getResult());
                }
                if (other.hasInfo()) {
                    setInfo(other.getInfo());
                }
                if (other.hasUuid()) {
                    setUuid(other.getUuid());
                }
                if (other.hasMacAddress()) {
                    setMacAddress(other.getMacAddress());
                }
                if (other.hasAreaId()) {
                    setAreaId(other.getAreaId());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.google.protobuf.UnknownFieldSet.Builder unknownFields
                        = com.google.protobuf.UnknownFieldSet.newBuilder(
                                this.getUnknownFields());
                while (true) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            this.setUnknownFields(unknownFields.build());
                            onChanged();
                            return this;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                this.setUnknownFields(unknownFields.build());
                                onChanged();
                                return this;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            result_ = input.readSInt32();
                            break;
                        }
                        case 18: {
                            bitField0_ |= 0x00000002;
                            info_ = input.readBytes();
                            break;
                        }
                        case 24: {
                            bitField0_ |= 0x00000004;
                            uuid_ = input.readInt64();
                            break;
                        }
                        case 34: {
                            bitField0_ |= 0x00000008;
                            macAddress_ = input.readBytes();
                            break;
                        }
                        case 40: {
                            bitField0_ |= 0x00000010;
                            areaId_ = input.readInt32();
                            break;
                        }
                    }
                }
            }

            private int bitField0_;

            // optional sint32 result = 1;
            private int result_;

            public boolean hasResult() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            public int getResult() {
                return result_;
            }

            public Builder setResult(int value) {
                bitField0_ |= 0x00000001;
                result_ = value;
                onChanged();
                return this;
            }

            public Builder clearResult() {
                bitField0_ = (bitField0_ & ~0x00000001);
                result_ = 0;
                onChanged();
                return this;
            }

            // optional string info = 2;
            private java.lang.Object info_ = "";

            public boolean hasInfo() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            public String getInfo() {
                java.lang.Object ref = info_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    info_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            public Builder setInfo(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                info_ = value;
                onChanged();
                return this;
            }

            public Builder clearInfo() {
                bitField0_ = (bitField0_ & ~0x00000002);
                info_ = getDefaultInstance().getInfo();
                onChanged();
                return this;
            }

            void setInfo(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000002;
                info_ = value;
                onChanged();
            }

            // optional int64 uuid = 3;
            private long uuid_;

            public boolean hasUuid() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            public long getUuid() {
                return uuid_;
            }

            public Builder setUuid(long value) {
                bitField0_ |= 0x00000004;
                uuid_ = value;
                onChanged();
                return this;
            }

            public Builder clearUuid() {
                bitField0_ = (bitField0_ & ~0x00000004);
                uuid_ = 0L;
                onChanged();
                return this;
            }

            // optional string macAddress = 4;
            private java.lang.Object macAddress_ = "";

            public boolean hasMacAddress() {
                return ((bitField0_ & 0x00000008) == 0x00000008);
            }

            public String getMacAddress() {
                java.lang.Object ref = macAddress_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    macAddress_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            public Builder setMacAddress(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000008;
                macAddress_ = value;
                onChanged();
                return this;
            }

            public Builder clearMacAddress() {
                bitField0_ = (bitField0_ & ~0x00000008);
                macAddress_ = getDefaultInstance().getMacAddress();
                onChanged();
                return this;
            }

            void setMacAddress(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000008;
                macAddress_ = value;
                onChanged();
            }

            // optional int32 area_id = 5;
            private int areaId_;

            public boolean hasAreaId() {
                return ((bitField0_ & 0x00000010) == 0x00000010);
            }

            public int getAreaId() {
                return areaId_;
            }

            public Builder setAreaId(int value) {
                bitField0_ |= 0x00000010;
                areaId_ = value;
                onChanged();
                return this;
            }

            public Builder clearAreaId() {
                bitField0_ = (bitField0_ & ~0x00000010);
                areaId_ = 0;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:message.CreateUUIDResponse)
        }

        static {
            defaultInstance = new CreateUUIDResponse(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:message.CreateUUIDResponse)
    }

    private static com.google.protobuf.Descriptors.Descriptor internal_static_message_CreateUUIDRequest_descriptor;
    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_message_CreateUUIDRequest_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.Descriptor internal_static_message_CreateUUIDResponse_descriptor;
    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_message_CreateUUIDResponse_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
            getDescriptor() {
        return descriptor;
    }
    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

    static {
        java.lang.String[] descriptorData = {
            "\n\026UUIDsSelfBuilder.proto\022\007message\"N\n\021Cre"
            + "ateUUIDRequest\022\024\n\014serverNumber\030\001 \001(\t\022\022\n\n"
            + "macAddress\030\002 \001(\t\022\017\n\007area_id\030\003 \001(\005\"e\n\022Cre"
            + "ateUUIDResponse\022\016\n\006result\030\001 \001(\021\022\014\n\004info\030"
            + "\002 \001(\t\022\014\n\004uuid\030\003 \001(\003\022\022\n\nmacAddress\030\004 \001(\t\022"
            + "\017\n\007area_id\030\005 \001(\005B.\n\032com.bw.application.m"
            + "essageB\020UUIDsSelfBuilder"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner
                = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
            public com.google.protobuf.ExtensionRegistry assignDescriptors(
                    com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                internal_static_message_CreateUUIDRequest_descriptor
                        = getDescriptor().getMessageTypes().get(0);
                internal_static_message_CreateUUIDRequest_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                        internal_static_message_CreateUUIDRequest_descriptor,
                        new java.lang.String[]{"ServerNumber", "MacAddress", "AreaId",},
                        com.bw.application.message.UUIDsSelfBuilder.CreateUUIDRequest.class,
                        com.bw.application.message.UUIDsSelfBuilder.CreateUUIDRequest.Builder.class);
                internal_static_message_CreateUUIDResponse_descriptor
                        = getDescriptor().getMessageTypes().get(1);
                internal_static_message_CreateUUIDResponse_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                        internal_static_message_CreateUUIDResponse_descriptor,
                        new java.lang.String[]{"Result", "Info", "Uuid", "MacAddress", "AreaId",},
                        com.bw.application.message.UUIDsSelfBuilder.CreateUUIDResponse.class,
                        com.bw.application.message.UUIDsSelfBuilder.CreateUUIDResponse.Builder.class);
                return null;
            }
        };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{}, assigner);
    }

    // @@protoc_insertion_point(outer_class_scope)
}
